#+STARTUP: overview
#+STARTUP: hidestars

* descr ============== stemmer для v.0.4 ===============
  определяет queries для samasa по окончанию
  начало 9 июня 2016, окончить к концу сентября
  todo в _todo.org


* 3 авг - tiNanta.js - तिङन्त
  - [ ] новый PD
  - [ ] passive

* subanta.js
  - [ ] start
  - [ ] причастия start


* diglossa.js
  - убрать всплывающее окно
  -

* v.0.4
  - v.0.4
  - css
  - MW чисто
  - Apte
  - строка - next и sandhi
  - новые глаголы прикрутить
  -



* 31 июля
  - поиграемся еще, passive, etc
  - как будет вести себя нестандарный tvar?
  -
  - но, главное. Дело сделано, нужно составить план выпуска v.0.4, и сделать. А игры - потом, и в процессе
  - [ ] соответствие DHATUS <<====
  - и план чтения О Душе
  - и план app-diglossa
  - и хорошо бы план разработки всего глагола
  -
  - ===================


* non-monosyllabic
2 'utkaRW' 'उत्कण्ठ्' '10' 'प'
2 'utkaRW' 'उत्कण्ठ्' '10' 'आ'
2 'uDras' 'उध्रस्' '10' 'प'
2 'uDras' 'उध्रस्' '10' 'आ'
2 'UrRu' 'ऊर्णु' '02' 'प'
2 'UrRu' 'ऊर्णु' '02' 'आ'
2 'olaRq' 'ओलण्ड्' '10' 'प'
2 'olaRq' 'ओलण्ड्' '10' 'आ'
2 'kumAr' 'कुमार्' '10' 'प'
2 'kumAr' 'कुमार्' '10' 'आ'
2 'gavez' 'गवेष्' '10' 'प'
2 'gavez' 'गवेष्' '10' 'आ'
2 'gepa' 'गेप' '01' 'आ'
2 'cakAs' 'चकास्' '02' 'प'
2 'ciri' 'चिरि' '05' 'प'
2 'jAgf' 'जागृ' '02' 'प'
2 'jiri' 'जिरि' '05' 'प'
3 'daridrA' 'दरिद्रा' '02' 'प'
2 'dIDI' 'दीधी' '02' 'आ'
2 'nivAs' 'निवास्' '10' 'प'
2 'nivAs' 'निवास्' '10' 'आ'
2 'palyUl' 'पल्यूल्' '10' 'प'
2 'palyUl' 'पल्यूल्' '10' 'आ'
2 'vAvft' 'वावृत्' '04' 'आ'
2 'vevI' 'वेवी' '02' 'आ'
2 'saNket' 'सङ्केत्' '10' 'प'
2 'saNket' 'सङ्केत्' '10' 'आ'
2 'saNgrAm' 'सङ्ग्राम्' '10' 'आ'
2 'samAj' 'समाज्' '10' 'प'
2 'samAj' 'समाज्' '10' 'आ'


* COnjugational: two tenses -present and imperfect- and the two moods - imperative and potential


* links *** http://sanskrit.jnu.ac.in/rstudents/mphil/
 - http://sanskrit.uohyd.ac.in/Corpus/guideline.html
 - http://sanskrit.uohyd.ac.in/Corpus/
 - http://sanskritlibrary.org/Sanskrit/pub/
 - http://www.sanskritworld.in/sanskrittool/SanskritVerb/tiGanta.html
 - https://github.com/drdhaval2785/sanskritverb
 - http://sanskrit.jnu.ac.in/tinanta/data-resources/
 - http://www.sanskritlibrary.org/Sanskrit/Vyakarana/Dhatupatha/mdhvindx/disp/mdhv_index.html#begin_char_12
 - http://sanskritdocuments.org/doc_giitaa/bgwords.html?lang=sa
 - file:///home/michael/web/morpheus/DOCS/TMP/dhaatupaatha/gaNa.html <=============
 - http://sanskrit.jnu.ac.in/rstudents/mphil/
 - http://www.thesanskritlanguage.com/lesson-25.html




* laN - augment
  - не понятно, как проверять наличие A? сначала нужно вычесть все приставки
  -


* stems & terminations
  - https://www.quora.com/How-are-the-verbs-in-Sanskrit-classified-As-well-what-are-the-most-common-tenses-and-how-are-verbs-usually-conjugated-in-those-tenses
  - http://learning-sanskrit.blogspot.ru/2012_05_01_archive.html?view=classic
  - http://www.sanskrit-sanscrito.com.ar/en/appendixes-verbs-appen-verbs-1-english-0/728

* pratyaya
  - http://sanatan-rigveda.blogspot.ru/p/verb-forms-krridantapada-in-chapter-3.html

In the following chapters we will study the following verb forms or धातुरुप (dhaaturupa).

    तुमुन् प्रत्यय (tumun pratyaya)
    क्त्वाच् प्रत्यय (ktvaach pratyaya)
    ल्यप् प्रत्यय (lyap pratyaya)
    ल्युट् प्रत्यय (lyuT pratyaya)
    क्तवतु प्रत्यय (ktavatu pratyaya)
    क्त प्रत्यय (kta pratyaya)
    अनीयर् प्रत्यय (aniiyar pratyaya)
    तव्यत् प्रत्यय (tavyat pratyaya)
    यत् प्रत्यय (yat pratyaya)
    शतृ प्रत्यय (shatRRi pratyaya)
    शानच् प्रत्यय (shaanach pratyaya)
    क्तिन् प्रत्यय (ktin pratyaya)
    घञ्ज् प्रत्यय (ghJNj pratyaya)
    खल् प्रत्यय (khal pratyaya)
