/*
 * laghu tin, sup
 */

var affixes = {};

affixes.tin =
 [ { flex: '', cflex: '', key: 'pl.2', pos: 'verb', la: 'lit', pada: 'par', plain: true, pl2: true },
  { flex: '', cflex: '', key: 'sg.1', pos: 'verb', la: 'lit', pada: 'par', plain: true, sg: true, first: true, sg1: true },
  { flex: '', cflex: '', key: 'sg.3', pos: 'verb', la: 'lit', pada: 'par', plain: true, sg: true, sg3: true },
  { flex: '', cflex: '', key: 'sg.2', pos: 'verb', la: 'lot', pada: 'par', plain: true, sg: true, sg2: true },
  { flex: 'ः', cflex: 'ः', key: 'sg.2', pos: 'verb', la: 'lan', pada: 'par', plain: true, sg: true, sg2: true },
  { flex: 'ति', cflex: 'अन्ति', key: 'pl.3', pos: 'verb', la: 'lat', pada: 'par', a: true, vow: true, pl3: true },
  { flex: 'ते', cflex: 'अते', key: 'du.3', pos: 'verb', la: 'lat', pada: 'atm', a: true, vow: true, plain: true, du3: true },
  { flex: 'ते', cflex: 'अन्ते', key: 'pl.3', pos: 'verb', la: 'lat', pada: 'atm', a: true, vow: true, pl3: true },
  { flex: 'थे', cflex: 'अथे', key: 'du.2', pos: 'verb', la: 'lat', pada: 'atm', a: true, vow: true, plain: true, du2: true },
  { flex: 'न्ति', cflex: 'अन्ति', key: 'pl.3', pos: 'verb', la: 'lat', pada: 'par', a: true, vow: true, plain: true, pl3: true },
  { flex: 'न्ते', cflex: 'अन्ते', key: 'pl.3', pos: 'verb', la: 'lat', pada: 'atm', a: true, vow: true, plain: true, pl3: true },
  { flex: 'ि', cflex: 'ए', key: 'sg.1', pos: 'verb', la: 'lan', pada: 'atm', vow: true, sg: true, first: true, sg1: true },
  { flex: 'े', cflex: 'ए', key: 'sg.1', pos: 'verb', la: 'lan', pada: 'atm', vow: true, plain: true, sg: true, first: true, sg1: true },
  { flex: 'े', cflex: 'ए', key: 'sg.1', pos: 'verb', la: 'lat', pada: 'atm', vow: true, plain: true, sg: true, first: true, sg1: true },
  { flex: 'टः', cflex: 'तः', key: 'du.3', pos: 'verb', la: 'lat', pada: 'par', du3: true },
  { flex: 'टि', cflex: 'ति', key: 'sg.3', pos: 'verb', la: 'lat', pada: 'par', sg: true, sg3: true },
  { flex: 'टु', cflex: 'तु', key: 'sg.3', pos: 'verb', la: 'lot', pada: 'par', sg: true, sg3: true },
  { flex: 'टे', cflex: 'ते', key: 'sg.3', pos: 'verb', la: 'lat', pada: 'atm', sg: true, sg3: true },
  { flex: 'ठ', cflex: 'थ', key: 'pl.2', pos: 'verb', la: 'lat', pada: 'par', pl2: true },
  { flex: 'ठ', cflex: 'थ', key: 'sg.2', pos: 'verb', la: 'lit', pada: 'par', sg: true, sg2: true },
  { flex: 'ठः', cflex: 'थः', key: 'du.2', pos: 'verb', la: 'lat', pada: 'par', du2: true },
  { flex: 'ढ', cflex: 'थ', key: 'pl.2', pos: 'verb', la: 'lat', pada: 'par', pl2: true },
  { flex: 'ढः', cflex: 'तः', key: 'du.3', pos: 'verb', la: 'lat', pada: 'par', du3: true },
  { flex: 'ढः', cflex: 'थः', key: 'du.2', pos: 'verb', la: 'lat', pada: 'par', du2: true },
  { flex: 'ढम्', cflex: 'तम्', key: 'du.2', pos: 'verb', la: 'lan', pada: 'par', du2: true },
  { flex: 'ढम्', cflex: 'तम्', key: 'du.2', pos: 'verb', la: 'lot', pada: 'par', du2: true },
  { flex: 'ढाम्', cflex: 'ताम्', key: 'du.3', pos: 'verb', la: 'lan', pada: 'par', du3: true },
  { flex: 'ढाम्', cflex: 'ताम्', key: 'sg.3', pos: 'verb', la: 'lot', pada: 'atm', sg: true, sg3: true },
  { flex: 'ढाम्', cflex: 'ताम्', key: 'du.3', pos: 'verb', la: 'lot', pada: 'par', du3: true },
  { flex: 'ढि', cflex: 'ति', key: 'sg.3', pos: 'verb', la: 'lat', pada: 'par', sg: true, sg3: true },
  { flex: 'ढि', cflex: '', key: 'sg.2', pos: 'verb', la: 'lot', pada: 'par', sg: true, sg2: true },
  { flex: 'ढु', cflex: 'तु', key: 'sg.3', pos: 'verb', la: 'lot', pada: 'par', sg: true, sg3: true },
  { flex: 'ढे', cflex: 'ते', key: 'sg.3', pos: 'verb', la: 'lat', pada: 'atm', sg: true, sg3: true },
  { flex: 'ढ्वम्', cflex: 'ध्वम्', key: 'pl.2', pos: 'verb', la: 'lot', pada: 'atm', pl2: true },
  { flex: 'ढ्वे', cflex: 'ध्वे', key: 'pl.2', pos: 'verb', la: 'lat', pada: 'atm', pl2: true },
  { flex: 'त', cflex: 'त', key: 'pl.3', pos: 'verb', la: 'lan', pada: 'atm', plain: true, pl3: true },
  { flex: 'त', cflex: 'त', key: 'sg.3', pos: 'verb', la: 'lan', pada: 'atm', plain: true, sg: true, sg3: true },
  { flex: 'त', cflex: 'त', key: 'pl.2', pos: 'verb', la: 'lan', pada: 'par', plain: true, pl2: true },
  { flex: 'त', cflex: 'त', key: 'pl.2', pos: 'verb', la: 'lot', pada: 'par', plain: true, pl2: true },
  { flex: 'तः', cflex: 'तः', key: 'du.3', pos: 'verb', la: 'lat', pada: 'par', plain: true, du3: true },
  { flex: 'तम्', cflex: 'तम्', key: 'du.2', pos: 'verb', la: 'lan', pada: 'par', plain: true, du2: true },
  { flex: 'तम्', cflex: 'तम्', key: 'du.2', pos: 'verb', la: 'lot', pada: 'par', plain: true, du2: true },
  { flex: 'ताम्', cflex: 'ताम्', key: 'du.3', pos: 'verb', la: 'lan', pada: 'par', plain: true, du3: true },
  { flex: 'ताम्', cflex: 'ताम्', key: 'sg.3', pos: 'verb', la: 'lot', pada: 'atm', plain: true, sg: true, sg3: true },
  { flex: 'ताम्', cflex: 'न्ताम्', key: 'pl.3', pos: 'verb', la: 'lot', pada: 'atm', pl3: true },
  { flex: 'ताम्', cflex: 'ताम्', key: 'du.3', pos: 'verb', la: 'lot', pada: 'par', plain: true, du3: true },
  { flex: 'ति', cflex: 'ति', key: 'sg.3', pos: 'verb', la: 'lat', pada: 'par', plain: true, sg: true, sg3: true },
  { flex: 'तु', cflex: 'तु', key: 'sg.3', pos: 'verb', la: 'lot', pada: 'par', plain: true, sg: true, sg3: true },
  { flex: 'तुः', cflex: 'तुः', key: 'du.3', pos: 'verb', la: 'lit', pada: 'par', plain: true, du3: true },
  { flex: 'ते', cflex: 'ते', key: 'sg.3', pos: 'verb', la: 'lat', pada: 'atm', plain: true, sg: true, sg3: true },
  { flex: 'त्', cflex: 'त्', key: 'sg.3', pos: 'verb', la: 'lan', pada: 'par', plain: true, sg: true, sg3: true },
  { flex: 'थ', cflex: 'थ', key: 'pl.2', pos: 'verb', la: 'lat', pada: 'par', plain: true, pl2: true },
  { flex: 'थ', cflex: 'थ', key: 'sg.2', pos: 'verb', la: 'lit', pada: 'par', plain: true, sg: true, sg2: true },
  { flex: 'थः', cflex: 'थः', key: 'du.2', pos: 'verb', la: 'lat', pada: 'par', plain: true, du2: true },
  { flex: 'थाः', cflex: 'थाः', key: 'sg.2', pos: 'verb', la: 'lan', pada: 'atm', plain: true, sg: true, sg2: true },
  { flex: 'थुः', cflex: 'थुः', key: 'du.2', pos: 'verb', la: 'lit', pada: 'par', plain: true, du2: true },
  { flex: 'ध', cflex: 'त', key: 'sg.3', pos: 'verb', la: 'lan', pada: 'atm', sg: true, sg3: true },
  { flex: 'ध', cflex: 'त', key: 'pl.2', pos: 'verb', la: 'lan', pada: 'par', pl2: true },
  { flex: 'ध', cflex: 'थ', key: 'pl.2', pos: 'verb', la: 'lat', pada: 'par', pl2: true },
  { flex: 'धः', cflex: 'तः', key: 'du.3', pos: 'verb', la: 'lat', pada: 'par', du3: true },
  { flex: 'धः', cflex: 'थः', key: 'du.2', pos: 'verb', la: 'lat', pada: 'par', du2: true },
  { flex: 'धम्', cflex: 'तम्', key: 'du.2', pos: 'verb', la: 'lan', pada: 'par', du2: true },
  { flex: 'धम्', cflex: 'तम्', key: 'du.2', pos: 'verb', la: 'lot', pada: 'par', du2: true },
  { flex: 'धाः', cflex: 'थाः', key: 'sg.2', pos: 'verb', la: 'lan', pada: 'atm', sg: true, sg2: true },
  { flex: 'धाम्', cflex: 'ताम्', key: 'du.3', pos: 'verb', la: 'lan', pada: 'par', du3: true },
  { flex: 'धाम्', cflex: 'ताम्', key: 'sg.3', pos: 'verb', la: 'lot', pada: 'atm', sg: true, sg3: true },
  { flex: 'धाम्', cflex: 'ताम्', key: 'du.3', pos: 'verb', la: 'lot', pada: 'par', du3: true },
  { flex: 'धि', cflex: 'ति', key: 'sg.3', pos: 'verb', la: 'lat', pada: 'par', sg: true, sg3: true },
  { flex: 'धि', cflex: '', key: 'sg.2', pos: 'verb', la: 'lot', pada: 'par', sg: true, sg2: true },
  { flex: 'धु', cflex: 'तु', key: 'sg.3', pos: 'verb', la: 'lot', pada: 'par', sg: true, sg3: true },
  { flex: 'धे', cflex: 'ते', key: 'sg.3', pos: 'verb', la: 'lat', pada: 'atm', sg: true, sg3: true },
  { flex: 'ध्वम्', cflex: 'ध्वम्', key: 'pl.2', pos: 'verb', la: 'lan', pada: 'atm', plain: true, pl2: true },
  { flex: 'ध्वम्', cflex: 'ध्वम्', key: 'pl.2', pos: 'verb', la: 'lot', pada: 'atm', plain: true, pl2: true },
  { flex: 'ध्वे', cflex: 'ध्वे', key: 'pl.2', pos: 'verb', la: 'lat', pada: 'atm', plain: true, pl2: true },
  { flex: 'ध्वे', cflex: 'ध्वे', key: 'pl.2', pos: 'verb', la: 'lit', pada: 'atm', plain: true, pl2: true },
  { flex: 'न्', cflex: 'न्', key: 'pl.3', pos: 'verb', la: 'lan', pada: 'par', plain: true, pl3: true },
  { flex: 'न्त', cflex: 'त', key: 'pl.3', pos: 'verb', la: 'lan', pada: 'atm', pl3: true },
  { flex: 'न्ताम्', cflex: 'न्ताम्', key: 'pl.3', pos: 'verb', la: 'lot', pada: 'atm', plain: true, pl3: true },
  { flex: 'न्तु', cflex: 'न्तु', key: 'pl.3', pos: 'verb', la: 'lot', pada: 'par', plain: true, pl3: true },
  { flex: 'म', cflex: 'म', key: 'pl.1', pos: 'verb', la: 'lan', pada: 'par', plain: true, first: true, pl1: true },
  { flex: 'म', cflex: 'म', key: 'pl.1', pos: 'verb', la: 'lit', pada: 'par', plain: true, first: true, pl1: true },
  { flex: 'मः', cflex: 'मः', key: 'pl.1', pos: 'verb', la: 'lat', pada: 'par', plain: true, first: true, pl1: true },
  { flex: 'महि', cflex: 'महि', key: 'pl.1', pos: 'verb', la: 'lan', pada: 'atm', plain: true, first: true, pl1: true },
  { flex: 'महे', cflex: 'महे', key: 'pl.1', pos: 'verb', la: 'lat', pada: 'atm', plain: true, first: true, pl1: true },
  { flex: 'महे', cflex: 'महे', key: 'pl.1', pos: 'verb', la: 'lit', pada: 'atm', plain: true, first: true, pl1: true },

   { flex: 'ामि', cflex: 'ामि', key: 'sg.1', pos: 'verb', la: 'lat', pada: 'par', plain: true, sg: true, first: true, sg1: true },
  { flex: 'म्', cflex: 'म्', key: 'sg.1', pos: 'verb', la: 'lan', pada: 'par', plain: true, sg: true, first: true, sg1: true },
  { flex: 'याः', cflex: 'याः', key: 'sg.2', pos: 'verb', la: 'lin', pada: 'par', plain: true, sg: true, sg2: true },
  { flex: 'यात', cflex: 'यात', key: 'pl.2', pos: 'verb', la: 'lin', pada: 'par', plain: true, pl2: true },
  { flex: 'यातम्', cflex: 'यातम्', key: 'du.2', pos: 'verb', la: 'lin', pada: 'par', plain: true, du2: true },
  { flex: 'याताम्', cflex: 'याताम्', key: 'du.3', pos: 'verb', la: 'lin', pada: 'par', plain: true, du3: true },
  { flex: 'यात्', cflex: 'यात्', key: 'sg.3', pos: 'verb', la: 'lin', pada: 'par', plain: true, sg: true, sg3: true },
  { flex: 'याम', cflex: 'याम', key: 'pl.1', pos: 'verb', la: 'lin', pada: 'par', plain: true, first: true, pl1: true },
  { flex: 'याम्', cflex: 'याम्', key: 'sg.1', pos: 'verb', la: 'lin', pada: 'par', plain: true, sg: true, first: true, sg1: true },
  { flex: 'याव', cflex: 'याव', key: 'du.1', pos: 'verb', la: 'lin', pada: 'par', plain: true, first: true, du1: true },
  { flex: 'युः', cflex: 'युः', key: 'pl.3', pos: 'verb', la: 'lin', pada: 'par', plain: true, pl3: true },
  { flex: 'रे', cflex: 'रे', key: 'pl.3', pos: 'verb', la: 'lit', pada: 'atm', plain: true, pl3: true },
  { flex: 'व', cflex: 'व', key: 'du.1', pos: 'verb', la: 'lan', pada: 'par', plain: true, first: true, du1: true },
  { flex: 'व', cflex: 'व', key: 'du.1', pos: 'verb', la: 'lit', pada: 'par', plain: true, first: true, du1: true },
  { flex: 'वः', cflex: 'वः', key: 'du.1', pos: 'verb', la: 'lat', pada: 'par', plain: true, first: true, du1: true },
  { flex: 'वहि', cflex: 'वहि', key: 'du.1', pos: 'verb', la: 'lan', pada: 'atm', plain: true, first: true, du1: true },
  { flex: 'वहे', cflex: 'वहे', key: 'du.1', pos: 'verb', la: 'lat', pada: 'atm', plain: true, first: true, du1: true },
  { flex: 'वहे', cflex: 'वहे', key: 'du.1', pos: 'verb', la: 'lit', pada: 'atm', plain: true, first: true, du1: true },
  { flex: 'षि', cflex: 'सि', key: 'sg.2', pos: 'verb', la: 'lat', pada: 'par', sg: true, sg2: true },
  { flex: 'षे', cflex: 'से', key: 'sg.2', pos: 'verb', la: 'lat', pada: 'atm', sg: true, sg2: true },
  { flex: 'षे', cflex: 'षे', key: 'sg.2', pos: 'verb', la: 'lit', pada: 'atm', plain: true, sg: true, sg2: true },
  { flex: 'ष्व', cflex: 'स्व', key: 'sg.2', pos: 'verb', la: 'lot', pada: 'atm', sg: true, sg2: true },
  { flex: 'सि', cflex: 'सि', key: 'sg.2', pos: 'verb', la: 'lat', pada: 'par', plain: true, sg: true, sg2: true },
  { flex: 'से', cflex: 'से', key: 'sg.2', pos: 'verb', la: 'lat', pada: 'atm', plain: true, sg: true, sg2: true },
  { flex: 'स्व', cflex: 'स्व', key: 'sg.2', pos: 'verb', la: 'lot', pada: 'atm', plain: true, sg: true, sg2: true },
  { flex: 'हि', cflex: '', key: 'sg.2', pos: 'verb', la: 'lot', pada: 'par', sg: true, sg2: true },
  { flex: 'ाणि', cflex: 'ानि', key: 'sg.1', pos: 'verb', la: 'lot', pada: 'par', sg: true, first: true, sg1: true },
  { flex: 'ाताम्', cflex: 'ाताम्', key: 'du.3', pos: 'verb', la: 'lan', pada: 'atm', plain: true, du3: true },
  { flex: 'ाताम्', cflex: 'ेताम्', key: 'du.3', pos: 'verb', la: 'lot', pada: 'atm', du3: true },
  { flex: 'ाते', cflex: 'ाते', key: 'du.3', pos: 'verb', la: 'lit', pada: 'atm', plain: true, du3: true },
  { flex: 'ाथाम्', cflex: 'ाथाम्', key: 'du.2', pos: 'verb', la: 'lan', pada: 'atm', plain: true, du2: true },
  { flex: 'ाथाम्', cflex: 'ेथाम्', key: 'du.2', pos: 'verb', la: 'lot', pada: 'atm', du2: true },
  { flex: 'ाथे', cflex: 'ाथे', key: 'du.2', pos: 'verb', la: 'lit', pada: 'atm', plain: true, du2: true },
  { flex: 'ानि', cflex: 'ानि', key: 'sg.1', pos: 'verb', la: 'lot', pada: 'par', plain: true, sg: true, first: true, sg1: true },
  { flex: 'ाम', cflex: 'ाम', key: 'pl.1', pos: 'verb', la: 'lot', pada: 'par', plain: true, first: true, pl1: true },
  { flex: 'ामहै', cflex: 'ामहै', key: 'pl.1', pos: 'verb', la: 'lot', pada: 'atm', plain: true, first: true, pl1: true },
  { flex: 'ाव', cflex: 'ाव', key: 'du.1', pos: 'verb', la: 'lot', pada: 'par', plain: true, first: true, du1: true },
  { flex: 'ावहै', cflex: 'ावहै', key: 'du.1', pos: 'verb', la: 'lot', pada: 'atm', plain: true, first: true, du1: true },
  { flex: 'ीत', cflex: 'ीत', key: 'sg.3', pos: 'verb', la: 'lin', pada: 'atm', plain: true, sg: true, sg3: true },
  { flex: 'ीथाः', cflex: 'ीथाः', key: 'sg.2', pos: 'verb', la: 'lin', pada: 'atm', plain: true, sg: true, sg2: true },
  { flex: 'ीध्वम्', cflex: 'ीध्वम्', key: 'pl.2', pos: 'verb', la: 'lin', pada: 'atm', plain: true, pl2: true },
  { flex: 'ीमहि', cflex: 'ीमहि', key: 'pl.1', pos: 'verb', la: 'lin', pada: 'atm', plain: true, first: true, pl1: true },
  { flex: 'ीय', cflex: 'ीय', key: 'sg.1', pos: 'verb', la: 'lin', pada: 'atm', plain: true, sg: true, first: true, sg1: true },
  { flex: 'ीयाताम्', cflex: 'ीयाताम्', key: 'du.3', pos: 'verb', la: 'lin', pada: 'atm', plain: true, du3: true },
  { flex: 'ीयाथाम्', cflex: 'ीयाथाम्', key: 'du.2', pos: 'verb', la: 'lin', pada: 'atm', plain: true, du2: true },
  { flex: 'ीरन्', cflex: 'ीरन्', key: 'pl.3', pos: 'verb', la: 'lin', pada: 'atm', plain: true, pl3: true },
  { flex: 'ीवहि', cflex: 'ीवहि', key: 'du.1', pos: 'verb', la: 'lin', pada: 'atm', plain: true, first: true, du1: true },
  { flex: 'ुः', cflex: 'न्', key: 'pl.3', pos: 'verb', la: 'lan', pada: 'par', pl3: true },
  { flex: 'ुः', cflex: 'ुः', key: 'pl.3', pos: 'verb', la: 'lit', pada: 'par', plain: true, pl3: true },
  { flex: 'े', cflex: 'े', key: 'sg.1', pos: 'verb', la: 'lit', pada: 'atm', plain: true, sg: true, first: true, sg1: true },
  { flex: 'े', cflex: 'े', key: 'sg.3', pos: 'verb', la: 'lit', pada: 'atm', plain: true, sg: true, sg3: true },
  { flex: 'ेः', cflex: 'ेः', key: 'sg.2', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, sg: true, sg2: true },
  { flex: 'ेत', cflex: 'ेत', key: 'sg.3', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, sg: true, sg3: true },
  { flex: 'ेत', cflex: 'ेत', key: 'pl.2', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, pl2: true },
  { flex: 'ेतम्', cflex: 'ेतम्', key: 'du.2', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, du2: true },
  { flex: 'ेताम्', cflex: 'ाताम्', key: 'du.3', pos: 'verb', la: 'lan', pada: 'atm', du3: true },
  { flex: 'ेताम्', cflex: 'ेताम्', key: 'du.3', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, du3: true },
  { flex: 'ेताम्', cflex: 'ेताम्', key: 'du.3', pos: 'verb', la: 'lot', pada: 'atm', plain: true, du3: true },
  { flex: 'ेत्', cflex: 'ेत्', key: 'sg.3', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, sg: true, sg3: true },
  { flex: 'ेथाः', cflex: 'ेथाः', key: 'sg.2', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, sg: true, sg2: true },
  { flex: 'ेथाम्', cflex: 'ाथाम्', key: 'du.2', pos: 'verb', la: 'lan', pada: 'atm', du2: true },
  { flex: 'ेथाम्', cflex: 'ेथाम्', key: 'du.2', pos: 'verb', la: 'lot', pada: 'atm', plain: true, du2: true },
  { flex: 'ेध्वम्', cflex: 'ेध्वम्', key: 'pl.2', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, pl2: true },
  { flex: 'ेम', cflex: 'ेम', key: 'pl.1', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, first: true, pl1: true },
  { flex: 'ेमहि', cflex: 'ेमहि', key: 'pl.1', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, first: true, pl1: true },
  { flex: 'ेय', cflex: 'ेय', key: 'sg.1', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, sg: true, first: true, sg1: true },
  { flex: 'ेयम्', cflex: 'ेयम्', key: 'sg.1', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, sg: true, first: true, sg1: true },
  { flex: 'ेयाताम्', cflex: 'ेयाताम्', key: 'du.3', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, du3: true },
  { flex: 'ेयाथाम्', cflex: 'ेयाथाम्', key: 'du.2', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, du2: true },
  { flex: 'ेयुः', cflex: 'ेयुः', key: 'pl.3', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, pl3: true },
  { flex: 'ेरन्', cflex: 'ेरन्', key: 'pl.3', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, pl3: true },
  { flex: 'ेव', cflex: 'ेव', key: 'du.1', pos: 'verb', la: 'lin', pada: 'par', plain: true, thema: true, first: true, du1: true },
  { flex: 'ेवहि', cflex: 'ेवहि', key: 'du.1', pos: 'verb', la: 'lin', pada: 'atm', plain: true, thema: true, first: true, du1: true },
  { flex: 'ै', cflex: 'ै', key: 'sg.1', pos: 'verb', la: 'lot', pada: 'atm', plain: true, sg: true, first: true, sg1: true },
  { flex: 'ौ', cflex: '', key: 'sg.1', pos: 'verb', la: 'lit', pada: 'par', sg: true, first: true, sg1: true },
  { flex: 'ौ', cflex: '', key: 'sg.3', pos: 'verb', la: 'lit', pada: 'par', sg: true, sg3: true } ];


affixes.sup = {
    'masc': {
        'sg' : {
            'a': {
                'dict': '',
                'sg.nom': 'ः',
                'sg.acc': 'म्',
                'sg.ins': 'ेन-ेण-ञ',
                'sg.dat': 'ाय',
                'sg.abl': 'ात्',
                'sg.gen': 'स्य',
                'sg.loc': 'े',
                'sg.voc': '',
            } ,

            'E': {
                'dict': 'ै',
                'sg.nom': 'ाः',
                'sg.acc': 'ायम्',
                'sg.ins': 'ाया',
                'sg.dat': 'ाये',
                'sg.abl': 'ायः',
                'sg.gen': 'ायः',
                'sg.loc': 'ायि',
                'sg.voc': 'ाः',
            } ,

            'an': {
                'dict': 'न्',
                'sg.nom': 'ा',
                'sg.acc': 'ानम्',
                'sg.ins': 'ना-्ञा-णा', // Y+varama, why?
                'sg.dat': 'ने-णे-्ञे',
                'sg.abl': 'नः-णः-्ञः',
                'sg.gen': 'नः-णः-्ञः',
                'sg.loc': 'नि-णि-्ञि',
                'sg.voc': 'न्',
            } ,

            'at': {
                'dict': 'त्',
                'sg.nom': 'ान्-त्', // -t for dyumat - adj = make naman g=masc_at_.+_sg.acc
                'sg.acc': 'न्तम्-त्',
                'sg.ins': 'ता',
                'sg.dat': 'ते',
                'sg.abl': 'तः',
                'sg.gen': 'तः',
                'sg.loc': 'ति',
                'sg.voc': 'न्-त्',
            } ,

            'i': {
                'dict': 'ि',
                'sg.nom': 'िः',
                'sg.acc': 'िम्',
                'sg.ins': 'िना-िणा',
                'sg.dat': 'ये',
                'sg.abl': 'ेः',
                'sg.gen': 'ेः',
                'sg.loc': 'ौ',
                'sg.voc': 'े',
            } ,

            'in': {
                'dict': 'िन्',
                'sg.nom': 'ी',
                'sg.acc': 'िनम्',
                'sg.ins': 'िना',
                'sg.dat': 'िने',
                'sg.abl': 'िनः',
                'sg.gen': 'िनः',
                'sg.loc': 'िनि',
                'sg.voc': 'िन्',
            } ,

            'f': {
                'dict': 'ृ',
                'sg.nom': 'ा',
                'sg.acc': 'रम्-ारम्',
                'sg.ins': '्रा',
                'sg.dat': '्रे',
                'sg.abl': 'ुः',
                'sg.gen': 'ुः',
                'sg.loc': 'रि',
                'sg.voc': 'ः',
            } ,

            'u': {
                'dict': 'ु',
                'sg.nom': 'ुः',
                'sg.acc': 'ुम्',
                'sg.ins': 'ुना-ुणा',
                'sg.dat': 'वे',
                'sg.abl': 'ोः',
                'sg.gen': 'ोः',
                'sg.loc': 'ौ',
                'sg.voc': 'ो',
            } ,

            'us': {
                'dict': 'ुस्',
                'sg.nom': 'ुः',
                'sg.acc': 'ुषम्',
                'sg.ins': 'ुषा',
                'sg.dat': 'ुषे',
                'sg.abl': 'ुषः',
                'sg.gen': 'ुषः',
                'sg.loc': 'ुषि',
                'sg.voc': 'ुः',
            } ,

            // ==== consonants ===
            'd': {
                'dict': 'द्',
                'sg.nom': 'त्',
                'sg.acc': 'दम्',
                'sg.ins': 'दा',
                'sg.dat': 'दे',
                'sg.abl': 'दः',
                'sg.gen': 'दः',
                'sg.loc': 'दि',
                'sg.voc': 'त्',
            } ,

            't': { // cons
                'dict': 'त्',
                'sg.nom': 'त्',
                'sg.acc': 'तम्',
                'sg.ins': 'ता',
                'sg.dat': 'ते',
                'sg.abl': 'तः',
                'sg.gen': 'तः',
                'sg.loc': 'त',
                'sg.voc': 'त्',
            } ,

            'm': { // cons masc
                'dict': 'म्',
                'sg.nom': 'म्',
                'sg.acc': 'मम्',
                'sg.ins': 'मा',
                'sg.dat': 'मे',
                'sg.abl': 'मः',
                'sg.gen': 'मः',
                'sg.loc': 'मि',
                'sg.voc': 'म्',
            } ,

            'B': { // cons masc
                'dict': 'भ्',
                'sg.nom': 'प्',
                'sg.acc': 'भम्',
                'sg.ins': 'भा',
                'sg.dat': 'भे',
                'sg.abl': 'भः',
                'sg.gen': 'भः',
                'sg.loc': 'भि',
                'sg.voc': 'प्',
            } ,

            'S': { // cons
                'dict': 'श्',
                'sg.nom': 'ट्',
                'sg.acc': 'शम्',
                'sg.ins': 'शा',
                'sg.dat': 'शे',
                'sg.abl': 'शः',
                'sg.gen': 'शः',
                'sg.loc': 'शि',
                'sg.voc': 'ट्',
            } ,

            's': {
                'dict': 'स्',
                'sg.nom': 'ः',
                'sg.acc': 'सम्',
                'sg.ins': 'सा',
                'sg.dat': 'से',
                'sg.abl': 'सः',
                'sg.gen': 'सः',
                'sg.loc': 'सि',
                'sg.voc': 'ः',
            } ,


            // === palatal ===
            'j': {
                'dict': 'ज्',
                'sg.nom': 'ट्-ङ्',
                'sg.acc': 'जम्-ञ्जम्',
                'sg.ins': 'जा',
                'sg.dat': 'जे',
                'sg.abl': 'जः',
                'sg.gen': 'जः',
                'sg.loc': 'जि',
                'sg.voc': 'ट्-ङ्',
            } ,

            'c': {
                'dict': 'च्',
                'sg.nom': 'क्',
                'sg.acc': 'चम्',
                'sg.ins': 'चा',
                'sg.dat': 'चे',
                'sg.abl': 'चः',
                'sg.gen': 'चः',
                'sg.loc': 'चि',
                'sg.voc': 'क्',
            } ,

            'h': {
                'dict': 'ह्',
                'sg.nom': 'ट्',
                'sg.acc': 'हम्',
                'sg.ins': 'हा',
                'sg.dat': 'हे',
                'sg.abl': 'हः',
                'sg.gen': 'हः',
                'sg.loc': 'हि',
                'sg.voc': 'ट्',
            } ,


            // 'T': { // sg
            //     'dict': '',
            //     'sg.nom': '',
            //     'sg.acc': '',
            //     'sg.ins': '',
            //     'sg.dat': '',
            //     'sg.abl': '',
            //     'sg.gen': '',
            //     'sg.loc': '',
            //     'sg.voc': '',
            // } ,

        },

        'du' : { // masc
            'a': {
                'dict': '',
                'du.nom': 'ौ',
                'du.acc': 'ौ',
                'du.ins': 'ाभ्याम्',
                'du.dat': 'ाभ्याम्',
                'du.abl': 'ाभ्याम्',
                'du.gen': 'योः',
                'du.loc': 'योः',
                'du.voc': 'ौ',
            } ,

            'E': {
                'dict': 'ै',
                'du.nom': 'ायौ',
                'du.acc': 'ायौ',
                'du.ins': 'ाभ्याम्',
                'du.dat': 'ाभ्याम्',
                'du.abl': 'ाभ्याम्',
                'du.gen': 'ायोः',
                'du.loc': 'ायोः',
                'du.voc': 'ायौ',
            } ,

            'an': {
                'dict': 'न्',
                'du.nom': 'ानौ',
                'du.acc': 'ानौ',
                'du.ins': 'भ्याम्',
                'du.dat': 'भ्याम्',
                'du.abl': 'भ्याम्',
                'du.gen': '्ञोः-नोः',
                'du.loc': '्ञोः-नोः',
                'du.voc': 'ानौ',
            } ,

            'at': {
                'dict': 'त्',
                'du.nom': 'न्तौ-ती',
                'du.acc': 'न्तौ-ती',
                'du.ins': 'द्भ्याम्',
                'du.dat': 'द्भ्याम्',
                'du.abl': 'द्भ्याम्',
                'du.gen': 'तोः',
                'du.loc': 'तोः',
                'du.voc': 'न्तौ-ती',
            } ,

            'i': {
                'dict': 'ि',
                'du.nom': 'ी',
                'du.acc': 'ी',
                'du.ins': 'िभ्याम्',
                'du.dat': 'िभ्याम्',
                'du.abl': 'िभ्याम्',
                'du.gen': '्योः',
                'du.loc': '्योः',
                'du.voc': 'ी',
            } ,

            'u': {
                'dict': 'ु',
                'du.nom': 'ू',
                'du.acc': 'ू',
                'du.ins': 'ुभ्याम्',
                'du.dat': 'ुभ्याम्',
                'du.abl': 'ुभ्याम्',
                'du.gen': '्वोः',
                'du.loc': '्वोः',
                'du.voc': 'ू',
            } ,

            'f': {
                'dict': 'ृ',
                'du.nom': 'ारौ-रौ',
                'du.acc': 'ारौ-रौ',
                'du.ins': 'ृभ्याम्',
                'du.dat': 'ृभ्याम्',
                'du.abl': 'ृभ्याम्',
                'du.gen': '्रोः',
                'du.loc': '्रोः',
                'du.voc': 'ारौ-रौ',
            } ,

            's': {
                'dict': 'स्',
                'du.nom': 'सौ',
                'du.acc': 'सौ',
                'du.ins': 'र्भ्याम्',
                'du.dat': 'र्भ्याम्',
                'du.abl': 'र्भ्याम्',
                'du.gen': 'सोः',
                'du.loc': 'सोः',
                'du.voc': 'सौ',
            } ,

            'us': {
                'dict': 'ुस्',
                'du.nom': 'ुषौ',
                'du.acc': 'ुषौ',
                'du.ins': 'ुर्भ्याम्',
                'du.dat': 'ुर्भ्याम्',
                'du.abl': 'ुर्भ्याम्',
                'du.gen': 'ुषोः',
                'du.loc': 'ुषोः',
                'du.voc': 'ुषौ',
            } ,

            // ==== palatal ====

            'j': {
                'dict': 'ज्',
                'du.nom': 'जौ-ञ्जौ',
                'du.acc': 'जौ-ञ्जौ',
                'du.ins': 'ड्भ्याम्-ग्भ्याम्',
                'du.dat': 'ड्भ्याम्-ग्भ्याम्',
                'du.abl': 'ड्भ्याम्-ग्भ्याम्',
                'du.gen': 'जोः',
                'du.loc': 'जोः',
                'du.voc': 'जौ-ञ्जौ',
            } ,

            'c': {
                'dict': 'च्',
                'du.nom': 'चौ',
                'du.acc': 'चौ',
                'du.ins': 'ग्भ्याम्',
                'du.dat': 'ग्भ्याम्',
                'du.abl': 'ग्भ्याम्',
                'du.gen': 'चोः',
                'du.loc': 'चोः',
                'du.voc': 'चौ',
            } ,

            'h': {
                'dict': 'ह्',
                'du.nom': 'हौ',
                'du.acc': 'हौ',
                'du.ins': 'ड्भ्याम्',
                'du.dat': 'ड्भ्याम्',
                'du.abl': 'ड्भ्याम्',
                'du.gen': 'होः',
                'du.loc': 'होः',
                'du.voc': 'हौ',
            } ,

            // === conconants ===

            'd': {
                'dict': 'द्',
                'du.nom': 'दौ',
                'du.acc': 'दौ',
                'du.ins': 'द्भ्याम्',
                'du.dat': 'द्भ्याम्',
                'du.abl': 'द्भ्याम्',
                'du.gen': 'दोः',
                'du.loc': 'दोः',
                'du.voc': 'दौ',
            } ,

            't': {
                'dict': 'त्',
                'du.nom': 'तौ',
                'du.acc': 'तौ',
                'du.ins': 'द्भ्याम्',
                'du.dat': 'द्भ्याम्',
                'du.abl': 'द्भ्याम्',
                'du.gen': 'तोः',
                'du.loc': 'तोः',
                'du.voc': 'तौ',
            } ,

            'm': {
                'dict': 'म्',
                'du.nom': 'मौ',
                'du.acc': 'मौ',
                'du.ins': 'ंभ्याम्', // M
                'du.dat': 'ंभ्याम्',
                'du.abl': 'ंभ्याम्',
                'du.gen': 'मोः',
                'du.loc': 'मोः',
                'du.voc': 'मौ',
            } ,

            'B': {
                'dict': 'भ्',
                'du.nom': 'भौ',
                'du.acc': 'भौ',
                'du.ins': 'ब्भ्याम्',
                'du.dat': 'ब्भ्याम्',
                'du.abl': 'ब्भ्याम्',
                'du.gen': 'भोः',
                'du.loc': 'भोः',
                'du.voc': 'भौ',
            } ,

            'S': {
                'dict': 'श्',
                'du.nom': 'शौ',
                'du.acc': 'शौ',
                'du.ins': 'ड्भ्याम्',
                'du.dat': 'ड्भ्याम्',
                'du.abl': 'ड्भ्याम्',
                'du.gen': 'शोः',
                'du.loc': 'शोः',
                'du.voc': 'शौ',
            } ,

        },
        'pl' : {
            // === PL ===
            'a': {
                'dict': '',
                'pl.nom': 'ाः',
                'pl.acc': 'ान्',
                'pl.ins': 'ैः',
                'pl.dat': 'ेभ्यः',
                'pl.abl': 'ेभ्यः',
                'pl.gen': 'ानाम्-ाणाम्',
                'pl.loc': 'ेषु',
                'pl.voc': 'ाः',
            } ,

            'E': {
                'dict': 'ै',
                'pl.nom': 'ायः',
                'pl.acc': 'ायः',
                'pl.ins': 'ाभिः',
                'pl.dat': 'ाभ्यः',
                'pl.abl': 'ाभ्यः',
                'pl.gen': 'ायाम्',
                'pl.loc': 'ासु',
                'pl.voc': 'ायः',
            } ,

            'an': {
                'dict': 'न्',
                'pl.nom': 'ानः',
                'pl.acc': '्ञः-नः',
                'pl.ins': 'भिः',
                'pl.dat': 'भ्यः',
                'pl.abl': 'भ्यः',
                'pl.gen': '्ञाम्-नाम्',
                'pl.loc': 'सु',
                'pl.voc': 'ानः',
            } ,

            'at': {
                'dict': 'त्',
                'pl.nom': 'न्तः-न्ति',
                'pl.acc': 'तः-न्ति',
                'pl.ins': 'द्भिः',
                'pl.dat': 'द्भ्यः',
                'pl.abl': 'द्भ्यः',
                'pl.gen': 'ताम्',
                'pl.loc': 'त्सु',
                'pl.voc': 'न्तः-न्ति',
            } ,

            'i': {
                'dict': 'ि',
                'pl.nom': 'यः',
                'pl.acc': 'ीन्', // красногорск, карбышева, д 4, к 1 - 10-30  - 9:00
                'pl.ins': 'िभिः',
                'pl.dat': 'िभ्यः',
                'pl.abl': 'िभ्यः',
                'pl.gen': 'ीनाम्',
                'pl.loc': 'िषु',
                'pl.voc': 'यः',
            } ,

            'in': {
                'dict': 'िन्',
                'pl.nom': 'िनः',
                'pl.acc': 'िनः',
                'pl.ins': 'िभिः',
                'pl.dat': 'िभ्यः',
                'pl.abl': 'िभ्यः',
                'pl.gen': 'ीनाम्-ीणाम्',
                'pl.loc': 'िषु',
                'pl.voc': 'िनः',
            } ,

            'f': {
                'dict': 'ृ',
                'pl.nom': 'रः-ारः',
                'pl.acc': 'ॄन्',
                'pl.ins': 'ृभिः',
                'pl.dat': 'ृभ्यः',
                'pl.abl': 'ृभ्यः',
                'pl.gen': 'ॄणाम्',
                'pl.loc': 'ृषु',
                'pl.voc': 'रः-ारः',
            } ,

            'u': {
                'dict': 'ु',
                'pl.nom': 'वः',
                'pl.acc': 'ून्',
                'pl.ins': 'ुभिः',
                'pl.dat': 'ुभ्यः',
                'pl.abl': 'ुभ्यः',
                'pl.gen': 'ूणाम्-ूनाम्',
                'pl.loc': 'ुषु',
                'pl.voc': 'वः',
            } ,

            'us': {
                'dict': 'ुस्',
                'pl.nom': 'ुषः',
                'pl.acc': 'ुषः',
                'pl.ins': 'ुर्भिः',
                'pl.dat': 'ुर्भ्यः',
                'pl.abl': 'ुर्भ्यः',
                'pl.gen': 'ुषाम्',
                'pl.loc': 'ुःषु',
                'pl.voc': 'ुषः',
            } ,

            'j': { // palatal
                'dict': 'ज्',
                'pl.nom': 'जः-ञ्जः',
                'pl.acc': 'जः',
                'pl.ins': 'ड्भिः-ग्भिः',
                'pl.dat': 'ड्भ्यः-ग्भ्यः',
                'pl.abl': 'ड्भ्यः-ग्भ्यः',
                'pl.gen': 'जाम्',
                'pl.loc': 'ट्सु-क्षु',
                'pl.voc': 'जः-ञ्जः',
            } ,

            'c': { // palatal
                'dict': 'च्',
                'pl.nom': 'चः',
                'pl.acc': 'चः',
                'pl.ins': 'ग्भिः',
                'pl.dat': 'ग्भ्यः',
                'pl.abl': 'ग्भ्यः',
                'pl.gen': 'चाम्',
                'pl.loc': 'क्षु',
                'pl.voc': 'चः',
            } ,

            'h': { // palatal
                'dict': 'ह्',
                'pl.nom': 'हः',
                'pl.acc': 'हः',
                'pl.ins': 'ड्भिः',
                'pl.dat': 'ड्भ्यः',
                'pl.abl': 'ड्भ्यः',
                'pl.gen': 'हाम्',
                'pl.loc': 'ट्सु',
                'pl.voc': 'हः',
            } ,

            'd': { // cons
                'dict': 'द्',
                'pl.nom': 'दः',
                'pl.acc': 'दः',
                'pl.ins': 'द्भिः',
                'pl.dat': 'द्भ्यः',
                'pl.abl': 'द्भ्यः',
                'pl.gen': 'दाम्',
                'pl.loc': 'त्सु',
                'pl.voc': 'दः',
            } ,

            't': {
                'dict': 'त्',
                'pl.nom': 'तः',
                'pl.acc': 'तः',
                'pl.ins': 'द्भिः',
                'pl.dat': 'द्भ्यः',
                'pl.abl': 'द्भ्यः',
                'pl.gen': 'ताम्',
                'pl.loc': 'त्सु',
                'pl.voc': 'तः',
            } ,

            'm': { // cons
                'dict': 'म्',
                'pl.nom': 'मः',
                'pl.acc': 'मः',
                'pl.ins': 'ंभिः', // M
                'pl.dat': 'ंभ्यः',
                'pl.abl': 'ंभ्यः',
                'pl.gen': 'माम्',
                'pl.loc': 'ंसु',
                'pl.voc': 'मः',
            } ,

            'B': {
                'dict': 'भ्',
                'pl.nom': 'भः',
                'pl.acc': 'भः',
                'pl.ins': 'ब्भिः',
                'pl.dat': 'ब्भ्यः',
                'pl.abl': 'ब्भ्यः',
                'pl.gen': 'भाम्',
                'pl.loc': 'प्सु',
                'pl.voc': 'भः',
            } ,

            'S': {
                'dict': 'श्',
                'pl.nom': 'शः',
                'pl.acc': 'शः',
                'pl.ins': 'ड्भिः',
                'pl.dat': 'ड्भ्यः',
                'pl.abl': 'ड्भ्यः',
                'pl.gen': 'शाम्',
                'pl.loc': 'ट्सु',
                'pl.voc': 'शः',
            } ,

            's': {
                'dict': 'स्',
                'pl.nom': 'सः',
                'pl.acc': 'सः',
                'pl.ins': 'र्भिः',
                'pl.dat': 'र्भ्यः',
                'pl.abl': 'र्भ्यः',
                'pl.gen': 'साम्',
                'pl.loc': 'ःसु',
                'pl.voc': 'सः',
            } ,

        },

    },

    'fem': {
        'sg' : {

            'A': {
                'dict': 'ा',
                'sg.nom': 'ा',
                'sg.acc': 'ाम्',
                'sg.ins': 'या',
                'sg.dat': 'ायै',
                'sg.abl': 'ायाः',
                'sg.gen': 'ायाः',
                'sg.loc': 'ायाम्',
                'sg.voc': 'े',
            } ,

            'O': {
                'dict': 'ौ',
                'sg.nom': 'ौः',
                'sg.acc': 'ावम्',
                'sg.ins': 'ावा',
                'sg.dat': 'ावे',
                'sg.abl': 'ावः',
                'sg.gen': 'ावः',
                'sg.loc': 'ावि',
                'sg.voc': 'ौः',
            } ,

            'i': {
                'dict': 'ि',
                'sg.nom': 'िः',
                'sg.acc': 'िम्',
                'sg.ins': '्या',
                'sg.dat': 'ये-्यै',
                'sg.abl': 'ेः-्याः',
                'sg.gen': 'ेः-्याः',
                'sg.loc': 'ौ-्याम्',
                'sg.voc': 'े',
            } ,

            'I': {
                'dict': 'ी',
                'sg.nom': 'ी',
                'sg.acc': 'ियम्-ीम्',
                'sg.ins': 'िया-्या',
                'sg.dat': 'िये-ियै-्यै',
                'sg.abl': 'ियः-ियाः-्याः',
                'sg.gen': 'ियः-ियाः-्याः',
                'sg.loc': 'ियि-ियाम्-्याम्',
                'sg.voc': 'ीः-ि',
            } ,

            'r': {
                'dict': 'िर्',
                'sg.nom': 'ीः',
                'sg.acc': 'िरम्',
                'sg.ins': 'िरा',
                'sg.dat': 'िरे',
                'sg.abl': 'िरः',
                'sg.gen': 'िरः',
                'sg.loc': 'िरि',
                'sg.voc': 'ीः',
            } ,

            'u': {
                'dict': 'ु',
                'sg.nom': 'ुः',
                'sg.acc': 'ुम्',
                'sg.ins': '्वा',
                'sg.dat': 'वे-्वै',
                'sg.abl': 'ोः-्वाः',
                'sg.gen': 'ोः-्वाः',
                'sg.loc': 'ौ-्वाम्',
                'sg.voc': 'ो',
            } ,

            'U': {
                'dict': 'ू',
                'sg.nom': 'ूः',
                'sg.acc': 'ुवम्-ूम्',
                'sg.ins': 'ुवा-्वा',
                'sg.dat': 'ुवै-ुवे-्वै',
                'sg.abl': 'ुवः-ुवाः-्वाः',
                'sg.gen': 'ुवः-ुवाः-्वाः',
                'sg.loc': 'ुवि-ुवाम्-्वाम्',
                'sg.voc': 'ूः-ु',
            } ,

            // === fem sg consonants ===
            'c': {
                'dict': 'च्',
                'sg.nom': 'क्',
                'sg.acc': 'चम्',
                'sg.ins': 'चा',
                'sg.dat': 'चे',
                'sg.abl': 'चः',
                'sg.gen': 'चः',
                'sg.loc': 'चि',
                'sg.voc': 'क्',
            } ,

            'S': {
                'dict': 'श्',
                'sg.nom': 'क्',
                'sg.acc': 'शम्',
                'sg.ins': 'शा',
                'sg.dat': 'शे',
                'sg.abl': 'शः',
                'sg.gen': 'शः',
                'sg.loc': 'शि',
                'sg.voc': 'क्',
            } ,

            'p': {
                'dict': 'प्',
                'sg.nom': 'प्',
                'sg.acc': 'पम्',
                'sg.ins': 'पा',
                'sg.dat': 'पे',
                'sg.abl': 'पः',
                'sg.gen': 'पः',
                'sg.loc': 'पि',
                'sg.voc': 'प्',
            } ,

            'B': {
                'dict': 'भ्',
                'sg.nom': 'प्',
                'sg.acc': 'भम्',
                'sg.ins': 'भा',
                'sg.dat': 'भे',
                'sg.abl': 'भः',
                'sg.gen': 'भः',
                'sg.loc': 'भि',
                'sg.voc': 'प्',
            } ,

            'h': {
                'dict': 'ह्',
                'sg.nom': 'ट्-क्',
                'sg.acc': 'हम्',
                'sg.ins': 'हा',
                'sg.dat': 'हे',
                'sg.abl': 'हः',
                'sg.gen': 'हः',
                'sg.loc': 'हि',
                'sg.voc': 'ट्-क्',
            } ,

        }, // num

        'du' : { // fem

            'A': {
                'dict': 'ा',
                'du.nom': 'े',
                'du.acc': 'े',
                'du.ins': 'ाभ्याम्',
                'du.dat': 'ाभ्याम्',
                'du.abl': 'ाभ्याम्',
                'du.gen': 'योः',
                'du.loc': 'योः',
                'du.voc': 'े',
            } ,

            'O': {
                'dict': 'ौ',
                'du.nom': 'ावौ',
                'du.acc': 'ावौ',
                'du.ins': 'ौभ्याम्',
                'du.dat': 'ौभ्याम्',
                'du.abl': 'ौभ्याम्',
                'du.gen': 'ावोः',
                'du.loc': 'ावोः',
                'du.voc': 'ावौ',
            } ,

            'i': {
                'dict': 'ि',
                'du.nom': 'ी',
                'du.acc': 'ी',
                'du.ins': 'िभ्याम्',
                'du.dat': 'िभ्याम्',
                'du.abl': 'िभ्याम्',
                'du.gen': '्योः',
                'du.loc': '्योः',
                'du.voc': 'ी',
            } ,

            'I': {
                'dict': 'ी',
                'du.nom': 'ियौ-्यौ',
                'du.acc': 'ियौ-्यौ',
                'du.ins': 'ीभ्याम्',
                'du.dat': 'ीभ्याम्',
                'du.abl': 'ीभ्याम्',
                'du.gen': 'ियोः-्योः',
                'du.loc': 'ियोः-्योः',
                'du.voc': 'ियौ-्यौ',
            } ,

            'u': {
                'dict': 'ु',
                'du.nom': 'ू',
                'du.acc': 'ू',
                'du.ins': 'ुभ्याम्',
                'du.dat': 'ुभ्याम्',
                'du.abl': 'ुभ्याम्',
                'du.gen': '्वोः',
                'du.loc': '्वोः',
                'du.voc': 'ू',
            } ,

            'U': {
                'dict': 'ू',
                'du.nom': 'ुवौ-्वौ',
                'du.acc': 'ुवौ-्वौ',
                'du.ins': 'ूभ्याम्',
                'du.dat': 'ूभ्याम्',
                'du.abl': 'ूभ्याम्',
                'du.gen': 'ुवोः-्वोः',
                'du.loc': 'ुवोः-्वोः',
                'du.voc': 'ुवौ-्वौ',
            } ,


            // === consonants du fem ===
            'c': {
                'dict': 'च्',
                'du.nom': 'चौ',
                'du.acc': 'चौ',
                'du.ins': 'ग्भ्याम्',
                'du.dat': 'ग्भ्याम्',
                'du.abl': 'ग्भ्याम्',
                'du.gen': 'चोः',
                'du.loc': 'चोः',
                'du.voc': 'चौ',
            } ,

            'S': {
                'dict': 'श्',
                'du.nom': 'शौ',
                'du.acc': 'शौ',
                'du.ins': 'ग्भ्याम्',
                'du.dat': 'ग्भ्याम्',
                'du.abl': 'ग्भ्याम्',
                'du.gen': 'शोः',
                'du.loc': 'शोः',
                'du.voc': 'शौ',
            } ,

            'p': {
                'dict': 'प्',
                'du.nom': 'पौ',
                'du.acc': 'पौ',
                'du.ins': 'ब्भ्याम्',
                'du.dat': 'ब्भ्याम्',
                'du.abl': 'ब्भ्याम्',
                'du.gen': 'पोः',
                'du.loc': 'पोः',
                'du.voc': 'पौ',
            } ,

            'B': {
                'dict': 'भ्',
                'du.nom': 'भौ',
                'du.acc': 'भौ',
                'du.ins': 'ब्भ्याम्',
                'du.dat': 'ब्भ्याम्',
                'du.abl': 'ब्भ्याम्',
                'du.gen': 'भोः',
                'du.loc': 'भोः',
                'du.voc': 'भौ',
            } ,

            'h': {
                'dict': 'ह्',
                'du.nom': 'हौ',
                'du.acc': 'हौ',
                'du.ins': 'ड्भ्याम्-ग्भ्याम्',
                'du.dat': 'ड्भ्याम्-ग्भ्याम्',
                'du.abl': 'ड्भ्याम्-ग्भ्याम्',
                'du.gen': 'होः',
                'du.loc': 'होः',
                'du.voc': 'हौ',
            } ,

            'ir': {
                'dict': 'िर्',
                'du.nom': 'िरौ',
                'du.acc': 'िरौ',
                'du.ins': 'ीर्भ्याम्',
                'du.dat': 'ीर्भ्याम्',
                'du.abl': 'ीर्भ्याम्',
                'du.gen': 'िरोः',
                'du.loc': 'िरोः',
                'du.voc': 'िरौ',
            } ,

        },

        'pl' : { // fem

            'A': {
                'dict': 'ा',
                'pl.nom': 'ाः',
                'pl.acc': 'ाः',
                'pl.ins': 'ाभिः',
                'pl.dat': 'ाभ्यः',
                'pl.abl': 'ाभ्यः',
                'pl.gen': 'ानाम्',
                'pl.loc': 'ासु',
                'pl.voc': 'ाः',
            } ,

            'O': {
                'dict': 'ौ',
                'pl.nom': 'ावः',
                'pl.acc': 'ावः',
                'pl.ins': 'ौभिः',
                'pl.dat': 'ौभ्यः',
                'pl.abl': 'ौभ्यः',
                'pl.gen': 'ावाम्',
                'pl.loc': 'ौषु',
                'pl.voc': 'ावः',
            } ,

            'i': {
                'dict': 'ि',
                'pl.nom': 'यः',
                'pl.acc': 'ीः',
                'pl.ins': 'िभिः',
                'pl.dat': 'िभ्यः',
                'pl.abl': 'िभ्यः',
                'pl.gen': 'ीनाम्',
                'pl.loc': 'िषु',
                'pl.voc': 'यः',
            } ,

            'I': {
                'dict': 'ी',
                'pl.nom': 'ियः-्यः',
                'pl.acc': 'ियः-ीः',
                'pl.ins': 'ीभिः',
                'pl.dat': 'ीभ्यः',
                'pl.abl': 'ीभ्यः',
                'pl.gen': 'ियाम्-ीनाम्',
                'pl.loc': 'ीषु',
                'pl.voc': 'ियः-्यः',
            } ,

            'ir': {
                'dict': 'िर्',
                'pl.nom': 'िरः',
                'pl.acc': 'िरः',
                'pl.ins': 'ीर्भिः',
                'pl.dat': 'ीर्भ्यः',
                'pl.abl': 'ीर्भ्यः',
                'pl.gen': 'िराम्',
                'pl.loc': 'ीर्षु',
                'pl.voc': 'िरः',
            } ,

            'u': {
                'dict': 'ु',
                'pl.nom': 'वः',
                'pl.acc': 'ूः',
                'pl.ins': 'ुभिः',
                'pl.dat': 'ुभ्यः',
                'pl.abl': 'ुभ्यः',
                'pl.gen': 'ूनाम्',
                'pl.loc': 'ुषु',
                'pl.voc': 'वः',
            } ,

            'U': {
                'dict': 'ू',
                'pl.nom': 'ुवः-्वः',
                'pl.acc': 'ुवः-ूः',
                'pl.ins': 'ूभिः',
                'pl.dat': 'ूभ्यः',
                'pl.abl': 'ूभ्यः',
                'pl.gen': 'ूनाम्-ुवाम्',
                'pl.loc': 'ूषु',
                'pl.voc': 'ुवः-्वः',
            } ,

            // cons fem pl
            'c': {
                'dict': 'च्',
                'pl.nom': 'चः',
                'pl.acc': 'चः',
                'pl.ins': 'ग्भिः',
                'pl.dat': 'ग्भ्यः',
                'pl.abl': 'ग्भ्यः',
                'pl.gen': 'चाम्',
                'pl.loc': 'क्षु',
                'pl.voc': 'चः',
            } ,

            'S': {
                'dict': 'श्',
                'pl.nom': 'शः',
                'pl.acc': 'शः',
                'pl.ins': 'ग्भिः',
                'pl.dat': 'ग्भ्यः',
                'pl.abl': 'ग्भ्यः',
                'pl.gen': 'शाम्',
                'pl.loc': 'क्षु',
                'pl.voc': 'शः',
            } ,

            'p': {
                'dict': 'प्',
                'pl.nom': 'पः',
                'pl.acc': 'पः',
                'pl.ins': 'ब्भिः',
                'pl.dat': 'ब्भ्यः',
                'pl.abl': 'ब्भ्यः',
                'pl.gen': 'पाम्',
                'pl.loc': 'प्सु',
                'pl.voc': 'पः',
            } ,

            'B': {
                'dict': 'भ्',
                'pl.nom': 'भः',
                'pl.acc': 'भः',
                'pl.ins': 'ब्भिः',
                'pl.dat': 'ब्भ्यः',
                'pl.abl': 'ब्भ्यः',
                'pl.gen': 'भाम्',
                'pl.loc': 'प्सु',
                'pl.voc': 'भः',
            } ,

            'h': {
                'dict': 'ह्',
                'pl.nom': 'हः',
                'pl.acc': 'हः',
                'pl.ins': 'ड्भिः-ग्भिः',
                'pl.dat': 'ड्भ्यः-ग्भ्यः',
                'pl.abl': 'ड्भ्यः-ग्भ्यः',
                'pl.gen': 'हाम्',
                'pl.loc': 'ट्सु-क्षु',
                'pl.voc': 'हः',
            } ,

        },
    },

    'neut': {
        'sg' : {
            'a': {
                'dict': '',
                'sg.nom': 'म्',
                'sg.acc': 'म्',
                'sg.ins': 'ेन-ेण',
                'sg.dat': 'ाय',
                'sg.abl': 'ात्',
                'sg.gen': 'स्य',
                'sg.loc': 'े',
                'sg.voc': '',
            } ,

            'an': {
                'dict': 'न्',
                'sg.nom': '',
                'sg.acc': '',
                'sg.ins': '्ना-णा',
                'sg.dat': '्ने-णे',
                'sg.abl': '्नः-णः',
                'sg.gen': '्नः-णः',
                'sg.loc': 'नि-्नि-णि',
                'sg.voc': 'न्-',
            } ,

            'as': {
                'dict': 'स्',
                'sg.nom': 'ः-ाः',
                'sg.acc': 'ः',
                'sg.ins': 'सा',
                'sg.dat': 'से',
                'sg.abl': 'सः',
                'sg.gen': 'सः',
                'sg.loc': 'सि',
                'sg.voc': 'ः',
            } ,

            'at': {
                'dict': 'त्',
                'sg.nom': 'त्',
                'sg.acc': 'त्',
                'sg.ins': 'ता',
                'sg.dat': 'ते',
                'sg.abl': 'तः',
                'sg.gen': 'तः',
                'sg.loc': 'ति',
                'sg.voc': 'त्',
            } ,

            'i': {
                'dict': 'ि',
                'sg.nom': 'ि',
                'sg.acc': 'ि',
                'sg.ins': 'िणा',
                'sg.dat': 'िणे',
                'sg.abl': 'िणः',
                'sg.gen': 'िणः',
                'sg.loc': 'िणि',
                'sg.voc': 'े',
            } ,

            'is': {
                'dict': 'िस्',
                'sg.nom': 'िः',
                'sg.acc': 'िः',
                'sg.ins': 'िषा',
                'sg.dat': 'िषे',
                'sg.abl': 'िषः',
                'sg.gen': 'िषः',
                'sg.loc': 'िषि',
                'sg.voc': 'िः',
            } ,

            'r': {
                'dict': 'र्',
                'sg.nom': 'ः',
                'sg.acc': 'ः',
                'sg.ins': 'रा',
                'sg.dat': 'रे',
                'sg.abl': 'रः',
                'sg.gen': 'रः',
                'sg.loc': 'रि',
                'sg.voc': 'ः',
            } ,

            'u': {
                'dict': 'ु',
                'sg.nom': 'ु',
                'sg.acc': 'ु',
                'sg.ins': 'ुना',
                'sg.dat': 'ुने',
                'sg.abl': 'ुनः',
                'sg.gen': 'ुनः',
                'sg.loc': 'ुनि',
                'sg.voc': 'ो',
            } ,

            // === cons == neut.sg ===
            'fd': {
                'dict': 'ृद्',
                'sg.nom': 'ृद्',
                'sg.acc': 'ृद्',
                'sg.ins': 'ृदा',
                'sg.dat': '्र्दे',
                'sg.abl': '्र्दः',
                'sg.gen': '्र्दः',
                'sg.loc': '्र्दि',
                'sg.voc': 'ृद्',
            } ,

        }, // num

        'du' : { // neut
            'a': {
                'dict': '',
                'du.nom': 'े',
                'du.acc': 'े',
                'du.ins': 'ाभ्याम्',
                'du.dat': 'ाभ्याम्',
                'du.abl': 'ाभ्याम्',
                'du.gen': 'योः',
                'du.loc': 'योः',
                'du.voc': 'े',
            } ,

            'an': {
                'dict': 'न्',
                'du.nom': 'नी-्नी-णी-्णी',
                'du.acc': 'नी-्नी-णी-्णी',
                'du.ins': 'भ्याम्',
                'du.dat': 'भ्याम्',
                'du.abl': 'भ्याम्',
                'du.gen': '्नोः-णोः',
                'du.loc': '्नोः-णोः',
                'du.voc': 'नी-्नी-णी-्णी',
            } ,

            'as': {
                'dict': 'स्',
                'du.nom': 'सी-सौ',
                'du.acc': 'सी-सौ',
                'du.ins': 'ोभ्याम्',
                'du.dat': 'ोभ्याम्',
                'du.abl': 'ोभ्याम्',
                'du.gen': 'सोः',
                'du.loc': 'सोः',
                'du.voc': 'सी-सौ',
            } ,

            'at': {
                'dict': 'त्',
                'du.nom': 'ती',
                'du.acc': 'ती',
                'du.ins': 'द्भ्याम्',
                'du.dat': 'द्भ्याम्',
                'du.abl': 'द्भ्याम्',
                'du.gen': 'तोः',
                'du.loc': 'तोः',
                'du.voc': 'ती',
            } ,

            'i': {
                'dict': 'ि',
                'du.nom': 'िणी',
                'du.acc': 'िणी',
                'du.ins': 'िभ्याम्',
                'du.dat': 'िभ्याम्',
                'du.abl': 'िभ्याम्',
                'du.gen': 'िणोः',
                'du.loc': 'िणोः',
                'du.voc': 'िणी',
            } ,

            'is': {
                'dict': 'िस्',
                'du.nom': 'िषी',
                'du.acc': 'िषी',
                'du.ins': 'िर्भ्याम्',
                'du.dat': 'िर्भ्याम्',
                'du.abl': 'िर्भ्याम्',
                'du.gen': 'िषोः',
                'du.loc': 'िषोः',
                'du.voc': 'िषी',
            } ,

            'r': {
                'dict': 'र्',
                'du.nom': 'री',
                'du.acc': 'री',
                'du.ins': 'र्भ्याम्',
                'du.dat': 'र्भ्याम्',
                'du.abl': 'र्भ्याम्',
                'du.gen': 'रोः',
                'du.loc': 'रोः',
                'du.voc': 'री',
            } ,

            'u': {
                'dict': 'ु',
                'du.nom': 'ुनी',
                'du.acc': 'ुनी',
                'du.ins': 'ुभ्याम्',
                'du.dat': 'ुभ्याम्',
                'du.abl': 'ुभ्याम्',
                'du.gen': 'ुनोः',
                'du.loc': 'ुनोः',
                'du.voc': 'ुनी',
            } ,

            // === cons == du  neut ==
            'fd': {
                'dict': 'ृद्',
                'du.nom': 'ृद्',
                'du.acc': 'ृद्',
                'du.ins': 'ृद्भ्याम्',
                'du.dat': '्र्द्भ्याम्',
                'du.abl': '्र्द्भ्याम्',
                'du.gen': '्र्दोः',
                'du.loc': '्र्दोः',
                'du.voc': 'ृद्',
            } ,

        }, // num

        'pl' : { // neut
            'a': {
                'dict': '',
                'pl.nom': 'ानि-ाणि',
                'pl.acc': 'ानि-ाणि',
                'pl.ins': 'ैः',
                'pl.dat': 'ेभ्यः',
                'pl.abl': 'ेभ्यः',
                'pl.gen': 'ानाम्-ाणाम्',
                'pl.loc': 'ेषु',
                'pl.voc': 'ानि-ाणि',
            } ,

            'an': {
                'dict': 'न्',
                'pl.nom': 'ानि-ाणि',
                'pl.acc': 'ानि-ाणि',
                'pl.ins': 'भिः',
                'pl.dat': 'भ्यः',
                'pl.abl': 'भ्यः',
                'pl.gen': '्नाम्-नाम्-णाम्-्णाम्',
                'pl.loc': 'सु',
                'pl.voc': 'ानि-ाणि',
            } ,

            'as': {
                'dict': 'स्',
                'pl.nom': 'ांसि-सः',
                'pl.acc': 'ांसि-सः',
                'pl.ins': 'ोभिः',
                'pl.dat': 'ोभ्यः',
                'pl.abl': 'ोभ्यः',
                'pl.gen': 'साम्',
                'pl.loc': 'ःसु',
                'pl.voc': 'ांसि-सः',
            } ,

            'at': {
                'dict': 'त्',
                'pl.nom': 'न्ति',
                'pl.acc': 'न्ति',
                'pl.ins': 'द्भिः',
                'pl.dat': 'द्भ्यः',
                'pl.abl': 'द्भ्यः',
                'pl.gen': 'ताम्',
                'pl.loc': 'त्सु',
                'pl.voc': 'न्ति',
            } ,

            'i': {
                'dict': 'ि',
                'pl.nom': 'ीणि',
                'pl.acc': 'ीणि',
                'pl.ins': 'िभिः',
                'pl.dat': 'िभ्यः',
                'pl.abl': 'िभ्यः',
                'pl.gen': 'ीणाम्',
                'pl.loc': 'िषु',
                'pl.voc': 'ीणि',
            } ,

            'is': {
                'dict': 'िस्',
                'pl.nom': 'ींषि',
                'pl.acc': 'ींषि',
                'pl.ins': 'िर्भिः',
                'pl.dat': 'िर्भ्यः',
                'pl.abl': 'िर्भ्यः',
                'pl.gen': 'िषाम्',
                'pl.loc': 'िःषु',
                'pl.voc': 'ींषि',
            } ,

            'r': {
                'dict': 'र्',
                'pl.nom': 'रि',
                'pl.acc': 'रि',
                'pl.ins': 'र्भिः',
                'pl.dat': 'र्भ्यः',
                'pl.abl': 'र्भ्यः',
                'pl.gen': 'राम्',
                'pl.loc': 'र्षु',
                'pl.voc': 'रि',
            } ,

            'u': {
                'dict': 'ु',
                'pl.nom': 'ूनि',
                'pl.acc': 'ूनि',
                'pl.ins': 'ुभिः',
                'pl.dat': 'ुभ्यः',
                'pl.abl': 'ुभ्यः',
                'pl.gen': 'ूनाम्',
                'pl.loc': 'ुषु',
                'pl.voc': 'ूनि',
            } ,

            // cons neut
            'fd': {
                'dict': 'ृद्',
                'pl.nom': 'ृद्',
                'pl.acc': 'ृदः',
                'pl.ins': '्र्द्भिः',
                'pl.dat': '्र्द्भ्यः',
                'pl.abl': '्र्द्भ्यः',
                'pl.gen': '्र्दाम्',
                'pl.loc': '्र्त्सु',
                'pl.voc': 'ृद्',
            } ,

        }, // num
    }, // gend
}

module.exports = affixes;
