var data = [
{ stem: 'भव', dhatu: 'भू', la: 'लट्', pada: 'परस्मै', tvar: 0 },
{ stem: 'अभव', dhatu: 'भू', la: 'लङ्', pada: 'परस्मै', tvar: 0 },
{ stem: 'बभ', dhatu: 'भू', la: 'लिट्', pada: 'परस्मै', tvar: 0 },
{ stem: 'अभू', dhatu: 'भू', la: 'लुङ्', pada: 'परस्मै', tvar: 0 },
{ stem: 'भविता', dhatu: 'भू', la: 'लुट्', pada: 'परस्मै', tvar: 0 },
{ stem: 'भविष्य', dhatu: 'भू', la: 'ऌट्', pada: 'परस्मै', tvar: 0 },
{ stem: 'भव', dhatu: 'भू', la: 'लोट्', pada: 'परस्मै', tvar: 0 },
{ stem: 'भवे',
  dhatu: 'भू',
  la: 'विधिलिङ्',
  pada: 'परस्मै',
  tvar: 0 },
{ stem: 'भूया',
  dhatu: 'भू',
  la: 'आशीर्लिङ्',
  pada: 'परस्मै',
  tvar: 0 },
{ stem: 'अभविष्य',
  dhatu: 'भू',
  la: 'ॡङ्',
  pada: 'परस्मै',
  tvar: 0 },
{ stem: 'एध', dhatu: 'एध', la: 'लट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'ऐध', dhatu: 'एध', la: 'लङ्', pada: 'आत्मने', tvar: 0 },
{ stem: 'एधाञ्चक',
  dhatu: 'एध',
  la: 'लिट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: '', dhatu: 'एध', la: 'लुङ्', pada: 'आत्मने', tvar: 0 },
{ stem: 'एधिता', dhatu: 'एध', la: 'लुट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'एधिष्य', dhatu: 'एध', la: 'ऌट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'एध', dhatu: 'एध', la: 'लोट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'एधे',
  dhatu: 'एध',
  la: 'विधिलिङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'एधिषी',
  dhatu: 'एध',
  la: 'आशीर्लिङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'ऐधिष्य', dhatu: 'एध', la: 'ॡङ्', pada: 'आत्मने', tvar: 0 },
{ stem: 'स्पर्ध',
  dhatu: 'स्पर्ध',
  la: 'लट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'अस्पर्ध',
  dhatu: 'स्पर्ध',
  la: 'लङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'पस्पर्ध',
  dhatu: 'स्पर्ध',
  la: 'लिट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'अस्पर्धि',
  dhatu: 'स्पर्ध',
  la: 'लुङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'स्पर्धिता',
  dhatu: 'स्पर्ध',
  la: 'लुट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'स्पर्धिष्य',
  dhatu: 'स्पर्ध',
  la: 'ऌट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'स्पर्ध',
  dhatu: 'स्पर्ध',
  la: 'लोट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'स्पर्धे',
  dhatu: 'स्पर्ध',
  la: 'विधिलिङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'स्पर्धिषी',
  dhatu: 'स्पर्ध',
  la: 'आशीर्लिङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'अस्पर्धिष्य',
  dhatu: 'स्पर्ध',
  la: 'ॡङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'गाध', dhatu: 'गाधृ', la: 'लट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'अगाध', dhatu: 'गाधृ', la: 'लङ्', pada: 'आत्मने', tvar: 0 },
{ stem: 'जगाध',
  dhatu: 'गाधृ',
  la: 'लिट्',
  pada: 'आत्मने',
  tvar: 1 },
{ stem: 'अगाधि',
  dhatu: 'गाधृ',
  la: 'लुङ्',
  pada: 'आत्मने',
  tvar: 1 },
{ stem: 'गाधिता',
  dhatu: 'गाधृ',
  la: 'लुट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'गाधिष्य',
  dhatu: 'गाधृ',
  la: 'ऌट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'गाध', dhatu: 'गाधृ', la: 'लोट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'गाधे',
  dhatu: 'गाधृ',
  la: 'विधिलिङ्',
  pada: 'आत्मने',
  tvar: 1 },
{ stem: 'गाधिषी',
  dhatu: 'गाधृ',
  la: 'आशीर्लिङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'अगाधिष्य',
  dhatu: 'गाधृ',
  la: 'ॡङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'बाध', dhatu: 'बाधृ', la: 'लट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'अबाध', dhatu: 'बाधृ', la: 'लङ्', pada: 'आत्मने', tvar: 0 },
{ stem: 'बबाध',
  dhatu: 'बाधृ',
  la: 'लिट्',
  pada: 'आत्मने',
  tvar: 1 },
{ stem: 'अबाधि',
  dhatu: 'बाधृ',
  la: 'लुङ्',
  pada: 'आत्मने',
  tvar: 1 },
{ stem: 'बाधिता',
  dhatu: 'बाधृ',
  la: 'लुट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'बाधिष्य',
  dhatu: 'बाधृ',
  la: 'ऌट्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'बाध', dhatu: 'बाधृ', la: 'लोट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'ब',
  dhatu: 'बाधृ',
  la: 'विधिलिङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'बाधिषी',
  dhatu: 'बाधृ',
  la: 'आशीर्लिङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'अबाधिष्य',
  dhatu: 'बाधृ',
  la: 'ॡङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'दध', dhatu: 'दध', la: 'लट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'अदध', dhatu: 'दध', la: 'लङ्', pada: 'आत्मने', tvar: 0 },
{ stem: 'दध', dhatu: 'दध', la: 'लिट्', pada: 'आत्मने', tvar: 1 },
{ stem: 'अदधि', dhatu: 'दध', la: 'लुङ्', pada: 'आत्मने', tvar: 1 },
{ stem: 'दधिता', dhatu: 'दध', la: 'लुट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'दधिष्य', dhatu: 'दध', la: 'ऌट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'दध', dhatu: 'दध', la: 'लोट्', pada: 'आत्मने', tvar: 0 },
{ stem: 'दधे',
  dhatu: 'दध',
  la: 'विधिलिङ्',
  pada: 'आत्मने',
  tvar: 1 },
{ stem: 'दधिषी',
  dhatu: 'दध',
  la: 'आशीर्लिङ्',
  pada: 'आत्मने',
  tvar: 0 },
{ stem: 'अदधिष्य',
  dhatu: 'दध',
  la: 'ॡङ्',
  pada: 'आत्मने',
  tvar: 0 },
]; 
exports = module.exports = data;