var data = [
{ stem: 'भव', dhatu: 'भू', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'एध', dhatu: 'एध्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्पर्ध',
  dhatu: 'स्पर्ध्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'गाध', dhatu: 'गाध्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'बाध', dhatu: 'बाध्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'दध', dhatu: 'दध्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्कुन्द',
  dhatu: 'स्कुद्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'वन्द', dhatu: 'वद्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'भन्द', dhatu: 'भद्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'मन्द', dhatu: 'मद्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्पन्द',
  dhatu: 'स्पद्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'क्लिन्द',
  dhatu: 'क्लद्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'मोद', dhatu: 'मुद्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'दद', dhatu: 'दद्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्वद', dhatu: 'ष्वद्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऊर्द', dhatu: 'उर्द्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'कूर्द',
  dhatu: 'कुर्द्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'सूद', dhatu: 'षूद्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ह्राद',
  dhatu: 'ह्राद्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'ह्लाद',
  dhatu: 'ह्लादी्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'स्वाद',
  dhatu: 'स्वाद्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'पर्द', dhatu: 'पर्द्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'यत', dhatu: 'यती्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'श्रन्थ',
  dhatu: 'श्रथ्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'कत्थ', dhatu: 'कत्थ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'चेत', dhatu: 'चित्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'खाद', dhatu: 'खाद्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'नर्द', dhatu: 'नर्द्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'गर्द', dhatu: 'गर्द्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'तर्द', dhatu: 'तर्द्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'कर्द', dhatu: 'कर्द्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'अन्त', dhatu: 'अत्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'इन्द', dhatu: 'इद्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'निन्द', dhatu: 'णिद्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'नन्द', dhatu: 'नद्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'चन्द', dhatu: 'चद्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'क्रन्द',
  dhatu: 'क्रद्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'क्लिन्द',
  dhatu: 'क्लिद्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'शुन्ध',
  dhatu: 'शुन्ध्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'लोक', dhatu: 'लोक्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'श्लोक',
  dhatu: 'श्लोक्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'शङ्क', dhatu: 'शक्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अङ्क', dhatu: 'अक्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'चक', dhatu: 'चक्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'लाघ', dhatu: 'लाघ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'श्लाघ',
  dhatu: 'श्लाघ्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'फक्क', dhatu: 'फक्क्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'तङ्क', dhatu: 'तक्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'बुक्क',
  dhatu: 'बुक्क्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'शाख', dhatu: 'शाख्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'ओख', dhatu: 'उख्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'उङ्ख', dhatu: 'उख्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'अङ्ग', dhatu: 'अग्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'वर्च', dhatu: 'वर्च्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'लोच', dhatu: 'लोच्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'पञ्च', dhatu: 'पच्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अर्ज', dhatu: 'ऋज्', la: 'लोट्', pada: 'आ.प', tvar: 1 },
{ stem: 'भर्ज', dhatu: 'भृजी्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'एज', dhatu: 'एज्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'भ्राज',
  dhatu: 'भ्राज्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'शोच', dhatu: 'शुच्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'कुञ्च',
  dhatu: 'कुञ्च्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'लुञ्च',
  dhatu: 'लुञ्च्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'अञ्च', dhatu: 'अञ्च्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'गुञ्ज', dhatu: 'गुज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'अर्च', dhatu: 'अर्च्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'वाञ्छ', dhatu: 'वाछ्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'मूर्च्छ',
  dhatu: 'मूर्छ्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'उञ्च्छ', dhatu: 'उछ्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'कूज', dhatu: 'कूज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'अर्ज', dhatu: 'अर्ज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'गर्ज', dhatu: 'गर्ज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'तर्ज', dhatu: 'तर्ज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'अज', dhatu: 'अज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'खञ्ज', dhatu: 'खज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'एज', dhatu: 'एज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'क्षय', dhatu: 'क्ष्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'व्रज', dhatu: 'व्रज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'वेष्ट',
  dhatu: 'वेष्ट्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'चेष्ट',
  dhatu: 'चेष्ट्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'घट्ट', dhatu: 'घट्ट्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्फोट',
  dhatu: 'स्फुट्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'हिण्ड', dhatu: 'हिड्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'पिण्ड', dhatu: 'पिड्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'चण्ड', dhatu: 'चड्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'तण्ड', dhatu: 'तड्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अट', dhatu: 'अट्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'रट', dhatu: 'रट्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'नट', dhatu: 'नट्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'लोट', dhatu: 'लुट्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'चेट', dhatu: 'चिट्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'अय', dhatu: 'ई्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'मण्ड', dhatu: 'मड्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'स्फोट',
  dhatu: 'स्फुटिर्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'मुण्ड', dhatu: 'मुड्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'पठ', dhatu: 'पठ्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'कुण्ठ', dhatu: 'कुठ्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'क्रीड',
  dhatu: 'क्रीड्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'तेप', dhatu: 'तिप्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'वेप', dhatu: 'वेप्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'त्रप',
  dhatu: 'त्रपूष्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'कम्प', dhatu: 'कप्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'क्लीब',
  dhatu: 'क्लीब्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'क्षीव',
  dhatu: 'क्षीव्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'क्राम',
  dhatu: 'क्रमु्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 1 },
{ stem: 'अय', dhatu: 'अय्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'दय', dhatu: 'दय्', la: 'लोट्', pada: 'आ.प', tvar: 2 },
{ stem: 'ऊय', dhatu: 'ऊयी्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'पूय', dhatu: 'पूयी्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्फाय',
  dhatu: 'स्फायी्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'ताय', dhatu: 'ताय्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'वल', dhatu: 'वल्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'कल', dhatu: 'कल्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'देव', dhatu: 'देव्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ईर्ष्य',
  dhatu: 'ईर्ष्य्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 1 },
{ stem: 'अल', dhatu: 'अल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'फल', dhatu: 'ञिफल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'मील', dhatu: 'मील्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'शूल', dhatu: 'शूल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'मूल', dhatu: 'मूल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'फल', dhatu: 'फल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'फुल्ल',
  dhatu: 'फुल्ल्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'खेल', dhatu: 'खेल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'स्खल', dhatu: 'स्खल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'दल', dhatu: 'दल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'चर', dhatu: 'चर्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'ष्ठीव',
  dhatu: 'ष्ठिवु्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'जय', dhatu: 'ज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'जीव', dhatu: 'जीव्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'पीव', dhatu: 'पीव्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'पूर्व',
  dhatu: 'पूर्व्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'चर्व', dhatu: 'चर्व्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'इन्व', dhatu: 'इव्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'अव', dhatu: 'अव्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'धाव', dhatu: 'धावु्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'शिक्ष',
  dhatu: 'शिक्ष्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'भिक्ष',
  dhatu: 'भिक्ष्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'दक्ष', dhatu: 'दक्ष्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'दीक्ष',
  dhatu: 'दीक्ष्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'ईक्ष', dhatu: 'ईक्ष्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ईष', dhatu: 'ईष्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'भाष', dhatu: 'भाष्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'भास', dhatu: 'भास्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'नास', dhatu: 'णास्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ग्रस', dhatu: 'ग्रसु्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ईह', dhatu: 'ईह्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'मंह', dhatu: 'मह्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'गर्ह', dhatu: 'गर्ह्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'काश', dhatu: 'काश्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऊह', dhatu: 'ऊह्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'गाह', dhatu: 'गाहू्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'गर्ह', dhatu: 'गृहू्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'त', dhatu: 'त्रैङ्', la: 'लोट्', pada: 'आ.प', tvar: 3 },
{ stem: 'याच', dhatu: 'याच्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'याच', dhatu: 'याच्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'पच', dhatu: 'डुपचष्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'पच', dhatu: 'डुपचष्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'रोच', dhatu: 'रुच्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'नय', dhatu: 'णीञ्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'नय', dhatu: 'णीञ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'हर', dhatu: 'ह्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'हर', dhatu: 'ह्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'वह', dhatu: 'वह्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'वह', dhatu: 'वह्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अर्ह', dhatu: 'अर्ह्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'कामय', dhatu: 'कमु्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'काङ्क्ष',
  dhatu: 'काक्ष्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 1 },
{ stem: 'कर्ष', dhatu: 'कृष्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'कल्प', dhatu: 'कृपू्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'गच्', dhatu: 'गम्', la: 'लोट्', pada: 'प.प', tvar: 2 },
{ stem: 'बोध', dhatu: 'बुध्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'स्मर', dhatu: 'स्म्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'शप', dhatu: 'शप्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'शप', dhatu: 'शप्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'बोध', dhatu: 'बुधिर्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'बोध', dhatu: 'बुधिर्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'तिष्ठ', dhatu: 'ष्ठ्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'नाथ', dhatu: 'नाथ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'यज', dhatu: 'यज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'यज', dhatu: 'यज्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'वद', dhatu: 'वद्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'वस', dhatu: 'वस्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'भज', dhatu: 'भज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'भज', dhatu: 'भज्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'पश्य', dhatu: 'दृशिर्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'तप', dhatu: 'तप्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'त्यज', dhatu: 'त्यज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'यच्छ', dhatu: 'दाण्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'पिब', dhatu: 'प्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'ग्लाय', dhatu: 'ग्लै', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'धर', dhatu: 'धृ', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'धर', dhatu: 'धृ', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'श्रय', dhatu: 'श्रिञ्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'श्रय', dhatu: 'श्रिञ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'चिकित्स',
  dhatu: 'कित्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'उक्ष', dhatu: 'उक्ष्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'कील', dhatu: 'कील्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'क्रोश',
  dhatu: 'क्रुश्',
  la: 'लोट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'क्षर', dhatu: 'क्षर्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'खन', dhatu: 'खन्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'खन', dhatu: 'खन्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'गर्व', dhatu: 'गर्व्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'जुगुप्स',
  dhatu: 'गुप्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'गाय', dhatu: 'गै्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'घट', dhatu: 'घट्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'जिघ्र', dhatu: 'घ्र्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'घूर्ण',
  dhatu: 'घूर्ण्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'चल', dhatu: 'चल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'चुम्ब', dhatu: 'चुब्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'चूष', dhatu: 'चूष्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'जप', dhatu: 'जप्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'जल्प', dhatu: 'जल्प्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'ज्वल', dhatu: 'ज्वल्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'तर', dhatu: 'तृ', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'दह', dhatu: 'दह्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'द्योत',
  dhatu: 'द्युत्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'ध्याय', dhatu: 'ध्यै्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'ध्वन', dhatu: 'ध्वन्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'पत', dhatu: 'पत्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'पण', dhatu: 'पण्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'नम', dhatu: 'णम्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'भर', dhatu: 'भृञ्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'भर', dhatu: 'भृञ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'भूष', dhatu: 'भूष्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'भ्रम', dhatu: 'भ्रमु्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'मन्थ', dhatu: 'मन्थ्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'मीमांस', dhatu: 'मान्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'रक्ष', dhatu: 'रक्ष्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'रम', dhatu: 'रमु्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'राज', dhatu: 'राज्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'राज', dhatu: 'राज्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'लङ्घ', dhatu: 'लघ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'लभ', dhatu: 'डुलभष्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'वर्त', dhatu: 'वृतु्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'वर्ध', dhatu: 'वृधु्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'वप', dhatu: 'वप्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'वप', dhatu: 'वप्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'वर्ष', dhatu: 'वृषु्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'व्यथ', dhatu: 'व्यथ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'सीद', dhatu: 'षद्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'सह', dhatu: 'षह्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'सर', dhatu: 'सृ', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'सेव', dhatu: 'षेव्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्रंस',
  dhatu: 'स्रंस्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'स्रव', dhatu: 'स्रु्', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'वम', dhatu: 'वम्', la: 'लोट्', pada: 'प.प', tvar: 0 },
{ stem: 'स्वर', dhatu: 'स्वृ', la: 'लोट्', pada: 'प.प', tvar: 1 },
{ stem: 'पव', dhatu: 'पूङ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'आरभ', dhatu: 'रभ्', la: 'लोट्', pada: 'आ.प', tvar: 0 },
{ stem: 'क्षोभ',
  dhatu: 'क्षुभ्',
  la: 'लोट्',
  pada: 'आ.प',
  tvar: 0 },
]; 
exports = module.exports = data;