var data = [
{ stem: 'भव', dhatu: 'भू', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अभव', dhatu: 'भू', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'एध', dhatu: 'एध्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऐध', dhatu: 'एध्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्पर्ध',
  dhatu: 'स्पर्ध्',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'अस्पर्ध',
  dhatu: 'स्पर्ध्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'गाध', dhatu: 'गाध्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अगाध', dhatu: 'गाध्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'बाध', dhatu: 'बाध्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अबाध', dhatu: 'बाध्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'दध', dhatu: 'दध्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अदध', dhatu: 'दध्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्कुन्द',
  dhatu: 'स्कुद्',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'अस्कुन्द',
  dhatu: 'स्कुद्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'वन्द', dhatu: 'वद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवन्द', dhatu: 'वद्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'भन्द', dhatu: 'भद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अभन्द', dhatu: 'भद्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'मन्द', dhatu: 'मद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अमन्द', dhatu: 'मद्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्पन्द', dhatu: 'स्पद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अस्पन्द',
  dhatu: 'स्पद्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'क्लिन्द',
  dhatu: 'क्लद्',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'अक्लिन्द',
  dhatu: 'क्लद्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'मोद', dhatu: 'मुद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अमोद', dhatu: 'मुद्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'दद', dhatu: 'दद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अदद', dhatu: 'दद्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्वद', dhatu: 'ष्वद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अस्वद', dhatu: 'ष्वद्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऊर्द', dhatu: 'उर्द्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ओर्द', dhatu: 'उर्द्', la: 'लङ्', pada: 'आ.प', tvar: 1 },
{ stem: 'कूर्द', dhatu: 'कुर्द्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अकूर्द',
  dhatu: 'कुर्द्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'सूद', dhatu: 'षूद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'असूद', dhatu: 'षूद्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'ह्राद', dhatu: 'ह्राद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अह्राद',
  dhatu: 'ह्राद्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'ह्लाद',
  dhatu: 'ह्लादी्',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'अह्लाद',
  dhatu: 'ह्लादी्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'स्वाद', dhatu: 'स्वाद्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अस्वाद',
  dhatu: 'स्वाद्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'पर्द', dhatu: 'पर्द्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अपर्द', dhatu: 'पर्द्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'यत', dhatu: 'यती्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अयत', dhatu: 'यती्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'श्रन्थ', dhatu: 'श्रथ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अश्रन्थ',
  dhatu: 'श्रथ्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'कत्थ', dhatu: 'कत्थ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अकत्थ', dhatu: 'कत्थ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'चेत', dhatu: 'चित्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचेत', dhatu: 'चित्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'खाद', dhatu: 'खाद्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अखा', dhatu: 'खाद्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'नर्द', dhatu: 'नर्द्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अनर्द', dhatu: 'नर्द्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'गर्द', dhatu: 'गर्द्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अगर्', dhatu: 'गर्द्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'तर्द', dhatu: 'तर्द्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अतर्', dhatu: 'तर्द्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'कर्द', dhatu: 'कर्द्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अकर्', dhatu: 'कर्द्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'अन्त', dhatu: 'अत्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आन्त', dhatu: 'अत्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'इन्द', dhatu: 'इद्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'ऐन्', dhatu: 'इद्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'निन्द', dhatu: 'णिद्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अनिन्', dhatu: 'णिद्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'नन्द', dhatu: 'नद्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अनन्', dhatu: 'नद्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'चन्द', dhatu: 'चद्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचन्', dhatu: 'चद्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'क्रन्द', dhatu: 'क्रद्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अक्रन्', dhatu: 'क्रद्', la: 'लङ्', pada: 'प.प', tvar: 1 },
{ stem: 'क्लिन्द',
  dhatu: 'क्लिद्',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'अक्लिन्',
  dhatu: 'क्लिद्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 1 },
{ stem: 'शुन्ध', dhatu: 'शुन्ध्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अशुन्ध',
  dhatu: 'शुन्ध्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'लोक', dhatu: 'लोक्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अलोक', dhatu: 'लोक्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'श्लोक', dhatu: 'श्लोक्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अश्लोक',
  dhatu: 'श्लोक्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'शङ्क', dhatu: 'शक्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अशङ्क', dhatu: 'शक्', la: 'लङ्', pada: 'आ.प', tvar: 2 },
{ stem: 'अङ्क', dhatu: 'अक्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'आङ्क', dhatu: 'अक्', la: 'लङ्', pada: 'आ.प', tvar: 2 },
{ stem: 'चक', dhatu: 'चक्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अचक', dhatu: 'चक्', la: 'लङ्', pada: 'आ.प', tvar: 2 },
{ stem: 'लाघ', dhatu: 'लाघ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अलाघ', dhatu: 'लाघ्', la: 'लङ्', pada: 'आ.प', tvar: 3 },
{ stem: 'श्लाघ', dhatu: 'श्लाघ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अश्लाघ',
  dhatu: 'श्लाघ्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 3 },
{ stem: 'फक्क', dhatu: 'फक्क्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अफक्क', dhatu: 'फक्क्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'तङ्क', dhatu: 'तक्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अतङ्क', dhatu: 'तक्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'बुक्क', dhatu: 'बुक्क्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अबुक्क',
  dhatu: 'बुक्क्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'शाख', dhatu: 'शाख्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अशाख', dhatu: 'शाख्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'ओख', dhatu: 'उख्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'औख', dhatu: 'उख्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'उङ्ख', dhatu: 'उख्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'औङ्ख', dhatu: 'उख्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'अङ्ग', dhatu: 'अग्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आङ्ग', dhatu: 'अग्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'वर्च', dhatu: 'वर्च्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवर्च', dhatu: 'वर्च्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'लोच', dhatu: 'लोच्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अलोच', dhatu: 'लोच्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'पञ्च', dhatu: 'पच्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अपञ्च', dhatu: 'पच्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'अर्ज', dhatu: 'ऋज्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'आर्ज', dhatu: 'ऋज्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'भर्ज', dhatu: 'भृजी्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अभर्ज', dhatu: 'भृजी्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'एज', dhatu: 'एज्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऐज', dhatu: 'एज्', la: 'लङ्', pada: 'आ.प', tvar: 1 },
{ stem: 'भ्राज', dhatu: 'भ्राज्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अभ्राज',
  dhatu: 'भ्राज्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'शोच', dhatu: 'शुच्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अशोच', dhatu: 'शुच्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'कुञ्च', dhatu: 'कुञ्च्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अकुञ्च',
  dhatu: 'कुञ्च्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'लुञ्च', dhatu: 'लुञ्च्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अल', dhatu: 'लुञ्च्', la: 'लङ्', pada: 'प.प', tvar: 2 },
{ stem: 'अञ्च', dhatu: 'अञ्च्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आञ्च', dhatu: 'अञ्च्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'गुञ्ज', dhatu: 'गुज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अगुञ्ज', dhatu: 'गुज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'अर्च', dhatu: 'अर्च्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आर्च', dhatu: 'अर्च्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'वाञ्छ', dhatu: 'वाछ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अव', dhatu: 'वाछ्', la: 'लङ्', pada: 'प.प', tvar: 3 },
{ stem: 'मूर्च्छ',
  dhatu: 'मूर्छ्',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'अमूर्च्छ',
  dhatu: 'मूर्छ्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'उञ्च्छ', dhatu: 'उछ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'औञ्च्छ', dhatu: 'उछ्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'कूज', dhatu: 'कूज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अकूज', dhatu: 'कूज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'अर्ज', dhatu: 'अर्ज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आर्ज', dhatu: 'अर्ज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'गर्ज', dhatu: 'गर्ज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अगर्ज', dhatu: 'गर्ज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'तर्ज', dhatu: 'तर्ज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अतर्ज', dhatu: 'तर्ज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'अज', dhatu: 'अज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आज', dhatu: 'अज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'खञ्ज', dhatu: 'खज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अखञ्ज', dhatu: 'खज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'एज', dhatu: 'एज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: '', dhatu: 'एज्', la: 'लङ्', pada: 'प.प', tvar: 4 },
{ stem: 'क्षय', dhatu: 'क्ष्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अक्षय', dhatu: 'क्ष्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'व्रज', dhatu: 'व्रज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अव्रज', dhatu: 'व्रज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'वेष्ट', dhatu: 'वेष्ट्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवेष्ट',
  dhatu: 'वेष्ट्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'चेष्ट', dhatu: 'चेष्ट्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अचेष्ट',
  dhatu: 'चेष्ट्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'घट्ट', dhatu: 'घट्ट्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अघट्ट', dhatu: 'घट्ट्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्फोट', dhatu: 'स्फुट्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अस्फोट',
  dhatu: 'स्फुट्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'हिण्ड', dhatu: 'हिड्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अहिण्ड', dhatu: 'हिड्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'पिण्ड', dhatu: 'पिड्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अपिण्ड', dhatu: 'पिड्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'चण्ड', dhatu: 'चड्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अचण्ड', dhatu: 'चड्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'तण्ड', dhatu: 'तड्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अतण्ड', dhatu: 'तड्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'अट', dhatu: 'अट्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आट', dhatu: 'अट्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'रट', dhatu: 'रट्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अरट', dhatu: 'रट्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'नट', dhatu: 'नट्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अनट', dhatu: 'नट्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'लोट', dhatu: 'लुट्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अलोट', dhatu: 'लुट्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'चेट', dhatu: 'चिट्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचेट', dhatu: 'चिट्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'अय', dhatu: 'ई्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आय', dhatu: 'ई्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'मण्ड', dhatu: 'मड्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अमण्ड', dhatu: 'मड्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'स्फोट',
  dhatu: 'स्फुटिर्',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'अस्फोट',
  dhatu: 'स्फुटिर्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'मुण्ड', dhatu: 'मुड्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अमुण्ड', dhatu: 'मुड्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'पठ', dhatu: 'पठ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अपठ', dhatu: 'पठ्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'कुण्ठ', dhatu: 'कुठ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अकुण्ठ', dhatu: 'कुठ्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'क्रीड', dhatu: 'क्रीड्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अक्रीड',
  dhatu: 'क्रीड्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'तेप', dhatu: 'तिप्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अतेप', dhatu: 'तिप्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'वेप', dhatu: 'वेप्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवेप', dhatu: 'वेप्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'त्रप', dhatu: 'त्रपूष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अत्रप',
  dhatu: 'त्रपूष्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'कम्प', dhatu: 'कप्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अकम्प', dhatu: 'कप्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'क्लीब', dhatu: 'क्लीब्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अक्ल', dhatu: 'क्लीब्', la: 'लङ्', pada: 'आ.प', tvar: 4 },
{ stem: 'क्षीव', dhatu: 'क्षीव्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अक्षीव',
  dhatu: 'क्षीव्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'क्राम', dhatu: 'क्रमु्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अक्राम',
  dhatu: 'क्रमु्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'अय', dhatu: 'अय्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'आय', dhatu: 'अय्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'दय', dhatu: 'दय्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अदय', dhatu: 'दय्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऊय', dhatu: 'ऊयी्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'औय', dhatu: 'ऊयी्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'पूय', dhatu: 'पूयी्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अपूय', dhatu: 'पूयी्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्फाय',
  dhatu: 'स्फायी्',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'अस्फाय',
  dhatu: 'स्फायी्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'ताय', dhatu: 'ताय्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अताय', dhatu: 'ताय्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'वल', dhatu: 'वल्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवल', dhatu: 'वल्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'कल', dhatu: 'कल्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अकल', dhatu: 'कल्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'देव', dhatu: 'देव्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अदेव', dhatu: 'देव्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'ईर्ष्य',
  dhatu: 'ईर्ष्य्',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'ऐर्ष्य',
  dhatu: 'ईर्ष्य्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'अल', dhatu: 'अल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आल', dhatu: 'अल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'फल', dhatu: 'ञिफल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अफल', dhatu: 'ञिफल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'मील', dhatu: 'मील्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अमील', dhatu: 'मील्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'शूल', dhatu: 'शूल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अशूल', dhatu: 'शूल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'मूल', dhatu: 'मूल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अमूल', dhatu: 'मूल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'फल', dhatu: 'फल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अफल', dhatu: 'फल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'फुल्ल', dhatu: 'फुल्ल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अफुल्ल',
  dhatu: 'फुल्ल्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'खेल', dhatu: 'खेल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अखेल', dhatu: 'खेल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'स्खल', dhatu: 'स्खल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अस्खल', dhatu: 'स्खल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'दल', dhatu: 'दल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अदल', dhatu: 'दल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'चर', dhatu: 'चर्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचर', dhatu: 'चर्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'ष्ठीव',
  dhatu: 'ष्ठिवु्',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'अष्ठीव',
  dhatu: 'ष्ठिवु्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'जय', dhatu: 'ज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अजय', dhatu: 'ज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'जीव', dhatu: 'जीव्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अजीव', dhatu: 'जीव्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'पीव', dhatu: 'पीव्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अपीव', dhatu: 'पीव्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'पूर्व', dhatu: 'पूर्व्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अपूर्व',
  dhatu: 'पूर्व्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'चर्व', dhatu: 'चर्व्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचर्व', dhatu: 'चर्व्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'इन्व', dhatu: 'इव्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'ऐन्व', dhatu: 'इव्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'अव', dhatu: 'अव्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आव', dhatu: 'अव्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'धाव', dhatu: 'धावु्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अधाव', dhatu: 'धावु्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'शिक्ष', dhatu: 'शिक्ष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अशिक्ष',
  dhatu: 'शिक्ष्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'भिक्ष', dhatu: 'भिक्ष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अभिक्ष',
  dhatu: 'भिक्ष्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'दक्ष', dhatu: 'दक्ष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अदक्ष', dhatu: 'दक्ष्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'दीक्ष', dhatu: 'दीक्ष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अदीक्ष',
  dhatu: 'दीक्ष्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'ईक्ष', dhatu: 'ईक्ष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऐक्ष', dhatu: 'ईक्ष्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'ईष', dhatu: 'ईष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऐष', dhatu: 'ईष्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'भाष', dhatu: 'भाष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अभाष', dhatu: 'भाष्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'भास', dhatu: 'भास्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अभास', dhatu: 'भास्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'नास', dhatu: 'णास्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अनास', dhatu: 'णास्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'ग्रस', dhatu: 'ग्रसु्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अग्रस', dhatu: 'ग्रसु्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'ईह', dhatu: 'ईह्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऐह', dhatu: 'ईह्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'मंह', dhatu: 'मह्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अमंह', dhatu: 'मह्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'गर्ह', dhatu: 'गर्ह्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अगर्ह', dhatu: 'गर्ह्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'काश', dhatu: 'काश्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अकाश', dhatu: 'काश्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'ऊह', dhatu: 'ऊह्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'औह', dhatu: 'ऊह्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'गाह', dhatu: 'गाहू्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अगाह', dhatu: 'गाहू्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'गर्ह', dhatu: 'गृहू्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अग्रह', dhatu: 'गृहू्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'त्राय', dhatu: 'त्रैङ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अत्राय',
  dhatu: 'त्रैङ्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'याच', dhatu: 'याच्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अयाच', dhatu: 'याच्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'याच', dhatu: 'याच्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अयाच', dhatu: 'याच्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'पच', dhatu: 'डुपचष्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अपच', dhatu: 'डुपचष्', la: 'लङ्', pada: 'प.प', tvar: 5 },
{ stem: 'पच', dhatu: 'डुपचष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अपच', dhatu: 'डुपचष्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'रोच', dhatu: 'रुच्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अरोच', dhatu: 'रुच्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'नय', dhatu: 'णीञ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अनय', dhatu: 'णीञ्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'नय', dhatu: 'णीञ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अनय', dhatu: 'णीञ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'हर', dhatu: 'ह्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अहर', dhatu: 'ह्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'हर', dhatu: 'ह्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अहर', dhatu: 'ह्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'वह', dhatu: 'वह्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अवह', dhatu: 'वह्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'वह', dhatu: 'वह्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवह', dhatu: 'वह्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'अर्ह', dhatu: 'अर्ह्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'आर्ह', dhatu: 'अर्ह्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'कामय', dhatu: 'कमु्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अकामय', dhatu: 'कमु्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'काङ्क्ष',
  dhatu: 'काक्ष्',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'अकाङ्क्ष',
  dhatu: 'काक्ष्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'कर्ष', dhatu: 'कृष्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अकर्ष', dhatu: 'कृष्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'कल्प', dhatu: 'कृपू्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अकल्प', dhatu: 'कृपू्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'गच्छ', dhatu: 'गम्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अगच्छ', dhatu: 'गम्', la: 'लङ्', pada: 'प.प', tvar: 5 },
{ stem: 'बोध', dhatu: 'बुध्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अबोध', dhatu: 'बुध्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'स्मर', dhatu: 'स्म्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अस्मर', dhatu: 'स्म्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'शप', dhatu: 'शप्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अशप', dhatu: 'शप्', la: 'लङ्', pada: 'प.प', tvar: 5 },
{ stem: 'शप', dhatu: 'शप्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अशप', dhatu: 'शप्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'बोध', dhatu: 'बुधिर्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अबोध', dhatu: 'बुधिर्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'बोध', dhatu: 'बुधिर्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अबोध', dhatu: 'बुधिर्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'तिष्ठ', dhatu: 'ष्ठ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अतिष्ठ', dhatu: 'ष्ठ्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'नाथ', dhatu: 'नाथ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अनाथ', dhatu: 'नाथ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'यज', dhatu: 'यज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अयज', dhatu: 'यज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'यज', dhatu: 'यज्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अयज', dhatu: 'यज्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'हस', dhatu: 'हसे्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अहस', dhatu: 'हसे्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'वद', dhatu: 'वद्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अवद', dhatu: 'वद्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'वस', dhatu: 'वस्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अवस', dhatu: 'वस्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'भज', dhatu: 'भज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अभज', dhatu: 'भज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'भज', dhatu: 'भज्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अभज', dhatu: 'भज्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'पश्य', dhatu: 'दृशिर्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अपश्य', dhatu: 'दृशिर्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'तप', dhatu: 'तप्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अतप', dhatu: 'तप्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'त्यज', dhatu: 'त्यज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अत्यज', dhatu: 'त्यज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'यच्छ', dhatu: 'दाण्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अयच्छ', dhatu: 'दाण्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'पिब', dhatu: 'प्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अपिब', dhatu: 'प्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'ग्लाय', dhatu: 'ग्लै', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अग्लाय', dhatu: 'ग्लै', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'धर', dhatu: 'धृ', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अधर', dhatu: 'धृ', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'धर', dhatu: 'धृ', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अधर', dhatu: 'धृ', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'श्रय', dhatu: 'श्रिञ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अश्रय', dhatu: 'श्रिञ्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'श्रय', dhatu: 'श्रिञ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अश्रय', dhatu: 'श्रिञ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'चिकित्स', dhatu: 'कित्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचिकित्स',
  dhatu: 'कित्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 5 },
{ stem: 'उक्ष', dhatu: 'उक्ष्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'औक्ष', dhatu: 'उक्ष्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'कील', dhatu: 'कील्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अकील', dhatu: 'कील्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'क्रोश', dhatu: 'क्रुश्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अक्रोश',
  dhatu: 'क्रुश्',
  la: 'लङ्',
  pada: 'प.प',
  tvar: 0 },
{ stem: 'क्षर', dhatu: 'क्षर्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अक्षर', dhatu: 'क्षर्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'खन', dhatu: 'खन्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अखन', dhatu: 'खन्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'खन', dhatu: 'खन्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अखन', dhatu: 'खन्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'गर्व', dhatu: 'गर्व्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अगर्व', dhatu: 'गर्व्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'जुगुप्स', dhatu: 'गुप्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अजुगुप्स',
  dhatu: 'गुप्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'गाय', dhatu: 'गै्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अगाय', dhatu: 'गै्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'घट', dhatu: 'घट्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अघट', dhatu: 'घट्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'जिघ्र', dhatu: 'घ्र्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अजिघ्र', dhatu: 'घ्र्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'घूर्ण', dhatu: 'घूर्ण्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अघूर्ण',
  dhatu: 'घूर्ण्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'चल', dhatu: 'चल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचल', dhatu: 'चल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'चुम्ब', dhatu: 'चुब्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचुम्ब', dhatu: 'चुब्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'चूष', dhatu: 'चूष्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अचूष', dhatu: 'चूष्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'जप', dhatu: 'जप्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अजप', dhatu: 'जप्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'जल्प', dhatu: 'जल्प्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अजल्प', dhatu: 'जल्प्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'ज्वल', dhatu: 'ज्वल्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अज्वल', dhatu: 'ज्वल्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'तर', dhatu: 'तृ', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अतर', dhatu: 'तृ', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'दह', dhatu: 'दह्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अदह', dhatu: 'दह्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'द्योत', dhatu: 'द्युत्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अद्योत',
  dhatu: 'द्युत्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'ध्याय', dhatu: 'ध्यै्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अध्याय', dhatu: 'ध्यै्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'ध्वन', dhatu: 'ध्वन्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अध्वन', dhatu: 'ध्वन्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'पत', dhatu: 'पत्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अपत', dhatu: 'पत्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'पण', dhatu: 'पण्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अपण', dhatu: 'पण्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'नम', dhatu: 'णम्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अनम', dhatu: 'णम्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'भर', dhatu: 'भृञ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अभर', dhatu: 'भृञ्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'भर', dhatu: 'भृञ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अभर', dhatu: 'भृञ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'भूष', dhatu: 'भूष्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अभूष', dhatu: 'भूष्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'भ्रम', dhatu: 'भ्रमु्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अभ्रम', dhatu: 'भ्रमु्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'मन्थ', dhatu: 'मन्थ्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अमन्थ', dhatu: 'मन्थ्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'मीमांस', dhatu: 'मान्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अमीमांस', dhatu: 'मान्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'रक्ष', dhatu: 'रक्ष्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अरक्ष', dhatu: 'रक्ष्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'रम', dhatu: 'रमु्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अरम', dhatu: 'रमु्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'राज', dhatu: 'राज्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अराज', dhatu: 'राज्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'राज', dhatu: 'राज्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अराज', dhatu: 'राज्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'लङ्घ', dhatu: 'लघ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अलङ्घ', dhatu: 'लघ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'लभ', dhatu: 'डुलभष्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अलभ', dhatu: 'डुलभष्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'वर्त', dhatu: 'वृतु्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवर्त', dhatu: 'वृतु्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'वर्ध', dhatu: 'वृधु्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवर्ध', dhatu: 'वृधु्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'वप', dhatu: 'वप्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अवप', dhatu: 'वप्', la: 'लङ्', pada: 'प.प', tvar: 5 },
{ stem: 'वप', dhatu: 'वप्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अवप', dhatu: 'वप्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'वर्ष', dhatu: 'वृषु्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अवर्ष', dhatu: 'वृषु्', la: 'लङ्', pada: 'प.प', tvar: 6 },
{ stem: 'व्यथ', dhatu: 'व्यथ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अव्यथ', dhatu: 'व्यथ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'शोभ', dhatu: 'शुभ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अशोभ', dhatu: 'शुभ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'सीद', dhatu: 'षद्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'असीद', dhatu: 'षद्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'सह', dhatu: 'षह्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'असह', dhatu: 'षह्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'सर', dhatu: 'सृ', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'असर', dhatu: 'सृ', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'सेव', dhatu: 'षेव्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'असेव', dhatu: 'षेव्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'स्रंस', dhatu: 'स्रंस्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अस्रंस',
  dhatu: 'स्रंस्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
{ stem: 'स्रव', dhatu: 'स्रु्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अस्रव', dhatu: 'स्रु्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'वम', dhatu: 'वम्', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अवम', dhatu: 'वम्', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'स्वर', dhatu: 'स्वृ', la: 'लट्', pada: 'प.प', tvar: 0 },
{ stem: 'अस्वर', dhatu: 'स्वृ', la: 'लङ्', pada: 'प.प', tvar: 0 },
{ stem: 'पव', dhatu: 'पूङ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अपव', dhatu: 'पूङ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'आरभ', dhatu: 'रभ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'आरभ', dhatu: 'रभ्', la: 'लङ्', pada: 'आ.प', tvar: 0 },
{ stem: 'क्षोभ', dhatu: 'क्षुभ्', la: 'लट्', pada: 'आ.प', tvar: 0 },
{ stem: 'अक्षोभ',
  dhatu: 'क्षुभ्',
  la: 'लङ्',
  pada: 'आ.प',
  tvar: 0 },
]; 
exports = module.exports = data;