var data = [
{ tin: 'दोग्धि',
  tip: 'तिप्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'दुग्धः',
  tip: 'तस्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'दुहन्ति',
  tip: 'झि',
  size: 7,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'धोक्षि',
  tip: 'सिप्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'दुग्धः',
  tip: 'थस्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'दुग्ध',
  tip: 'थ',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'दोह्मि',
  tip: 'मिप्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'दुह्वः',
  tip: 'वस्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'दुह्मः',
  tip: 'मस्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 0,
  canon: true },
{ tin: 'वीति',
  tip: 'तिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'ूतः',
  tip: 'तस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'ूवन्ति',
  tip: 'झि',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'वीषि',
  tip: 'सिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'ूथः',
  tip: 'थस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'ूथ',
  tip: 'थ',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'वीमि',
  tip: 'मिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'ूवः',
  tip: 'वस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'ूमः',
  tip: 'मस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 1,
  canon: true },
{ tin: 'ास्ति',
  tip: 'तिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'िष्टः',
  tip: 'तस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'ासति',
  tip: 'झि',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'ास्सि',
  tip: 'सिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'िष्ठः',
  tip: 'थस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'िष्ठ',
  tip: 'थ',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'ास्मि',
  tip: 'मिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'िष्वः',
  tip: 'वस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'िश्मः',
  tip: 'मस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 2,
  canon: true },
{ tin: 'त्ति',
  tip: 'तिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'त्तः',
  tip: 'तस्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'दन्ति',
  tip: 'झि',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'त्सि',
  tip: 'सिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'त्थः',
  tip: 'थस्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'त्थ',
  tip: 'थ',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'द्मि',
  tip: 'मिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'द्वः',
  tip: 'वस्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'द्मः',
  tip: 'मस्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 3,
  canon: true },
{ tin: 'अस्ति',
  tip: 'तिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'स्तः',
  tip: 'तस्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'सन्ति',
  tip: 'झि',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'असि',
  tip: 'सिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'स्थः',
  tip: 'थस्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'स्थ',
  tip: 'थ',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'अस्मि',
  tip: 'मिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'स्वः',
  tip: 'वस्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'स्मः',
  tip: 'मस्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 4,
  canon: true },
{ tin: 'ति',
  tip: 'तिप्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'तः',
  tip: 'तस्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'न्ति',
  tip: 'झि',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'सि',
  tip: 'सिप्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'थः',
  tip: 'थस्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'थ',
  tip: 'थ',
  size: 1,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'मि',
  tip: 'मिप्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'वः',
  tip: 'वस्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'मः',
  tip: 'मस्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 5,
  canon: true },
{ tin: 'एति',
  tip: 'तिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'इतः',
  tip: 'तस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'यन्ति',
  tip: 'झि',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'एषि',
  tip: 'सिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'इथः',
  tip: 'थस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'इथ',
  tip: 'थ',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'एमि',
  tip: 'मिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'इवः',
  tip: 'वस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'इमः',
  tip: 'मस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 6,
  canon: true },
{ tin: 'ोदिति',
  tip: 'तिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'ुदितः',
  tip: 'तस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'ुदन्ति',
  tip: 'झि',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'ोदिषि',
  tip: 'सिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'ुदिथः',
  tip: 'थस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'ुदिथ',
  tip: 'थ',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'ोदिमि',
  tip: 'मिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'ुदिवः',
  tip: 'वस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'ुदिमः',
  tip: 'मस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 7,
  canon: true },
{ tin: 'िति',
  tip: 'तिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 8,
  canon: true },
{ tin: 'ितः',
  tip: 'तस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 8,
  canon: true },
{ tin: 'िषि',
  tip: 'सिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 8,
  canon: true },
{ tin: 'िथः',
  tip: 'थस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 8,
  canon: true },
{ tin: 'िथ',
  tip: 'थ',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 8,
  canon: true },
{ tin: 'िमि',
  tip: 'मिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 8,
  canon: true },
{ tin: 'िवः',
  tip: 'वस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 8,
  canon: true },
{ tin: 'िमः',
  tip: 'मस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 8,
  canon: true },
{ tin: 'हन्ति',
  tip: 'तिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'हतः',
  tip: 'तस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'घ्नन्ति',
  tip: 'झि',
  size: 7,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'हंसि',
  tip: 'सिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'हथः',
  tip: 'थस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'हथ',
  tip: 'थ',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'हन्मि',
  tip: 'मिप्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'हन्वः',
  tip: 'वस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'हन्मः',
  tip: 'मस्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 9,
  canon: true },
{ tin: 'ौति',
  tip: 'तिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'ुतः',
  tip: 'तस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'ुवन्ति',
  tip: 'झि',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'ौषि',
  tip: 'सिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'ुथः',
  tip: 'थस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'ुथ',
  tip: 'थ',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'ौमि',
  tip: 'मिप्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'ुवः',
  tip: 'वस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'ुमः',
  tip: 'मस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 10,
  canon: true },
{ tin: 'र्ति',
  tip: 'तिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: 'ृतः',
  tip: 'तस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: '्रति',
  tip: 'झि',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: 'र्षि',
  tip: 'सिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: 'ृथः',
  tip: 'थस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: 'ृथ',
  tip: 'थ',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: 'र्मि',
  tip: 'मिप्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: 'ृवः',
  tip: 'वस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: 'ृमः',
  tip: 'मस्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'प.प',
  tvar: 11,
  canon: true },
{ tin: 'दुग्धे',
  tip: 'त',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'दुहाते',
  tip: 'आताम्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'दुहते',
  tip: 'झ',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'धुक्षे',
  tip: 'थास्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'दुहाथे',
  tip: 'आथाम्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'धुग्ध्वे',
  tip: 'ध्वम्',
  size: 8,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'दुहे',
  tip: 'इट्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'दुह्वहे',
  tip: 'वहिङ',
  size: 7,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'दुह्महे',
  tip: 'महिङ',
  size: 7,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 0,
  canon: true },
{ tin: 'ूते',
  tip: 'त',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ुवाते',
  tip: 'आताम्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ुवते',
  tip: 'झ',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ूषे',
  tip: 'थास्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ुवाथे',
  tip: 'आथाम्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ूध्वे',
  tip: 'ध्वम्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ुवे',
  tip: 'इट्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ूवहे',
  tip: 'वहिङ',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ूमहे',
  tip: 'महिङ',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 1,
  canon: true },
{ tin: 'ेते',
  tip: 'त',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'याते',
  tip: 'आताम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'ेरते',
  tip: 'झ',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'ेषे',
  tip: 'थास्',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'याथे',
  tip: 'आथाम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'ेध्वे',
  tip: 'ध्वम्',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'ये',
  tip: 'इट्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'ेवहे',
  tip: 'वहिङ',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'ेमहे',
  tip: 'महिङ',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 2,
  canon: true },
{ tin: 'ते',
  tip: 'त',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'वाते',
  tip: 'आताम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'वते',
  tip: 'झ',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'षे',
  tip: 'थास्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'वाथे',
  tip: 'आथाम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'ध्वे',
  tip: 'ध्वम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'वे',
  tip: 'इट्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'वहे',
  tip: 'वहिङ',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'महे',
  tip: 'महिङ',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 3,
  canon: true },
{ tin: 'ष्टे',
  tip: 'त',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'शाते',
  tip: 'आताम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'शते',
  tip: 'झ',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'शिषे',
  tip: 'थास्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'शाथे',
  tip: 'आथाम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'शिध्वे',
  tip: 'ध्वम्',
  size: 6,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'शे',
  tip: 'इट्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'श्वहे',
  tip: 'वहिङ',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'श्महे',
  tip: 'महिङ',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 4,
  canon: true },
{ tin: 'स्ते',
  tip: 'त',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 5,
  canon: true },
{ tin: 'साते',
  tip: 'आताम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 5,
  canon: true },
{ tin: 'सते',
  tip: 'झ',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 5,
  canon: true },
{ tin: 'स्से',
  tip: 'थास्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 5,
  canon: true },
{ tin: 'साथे',
  tip: 'आथाम्',
  size: 4,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 5,
  canon: true },
{ tin: 'से',
  tip: 'इट्',
  size: 2,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 5,
  canon: true },
{ tin: 'स्वहे',
  tip: 'वहिङ',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 5,
  canon: true },
{ tin: 'स्महे',
  tip: 'महिङ',
  size: 5,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 5,
  canon: true },
{ tin: 'यते',
  tip: 'झ',
  size: 3,
  gana: 'अदादि',
  la: 'लट्',
  pada: 'आ.प',
  tvar: 6,
  canon: true },
]; 
exports = module.exports = data;