var data = [
{ tin: 'ति', la: 'लट्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'तः', la: 'लट्', tip: 'तस्', size: 2, tvar: 0 },
{ tin: 'न्ति', la: 'लट्', tip: 'झि', size: 4, tvar: 0 },
{ tin: 'सि', la: 'लट्', tip: 'सिप्', size: 2, tvar: 0 },
{ tin: 'थः', la: 'लट्', tip: 'थस्', size: 2, tvar: 0 },
{ tin: 'थ', la: 'लट्', tip: 'थ', size: 1, tvar: 0 },
{ tin: 'ामि', la: 'लट्', tip: 'मिप्', size: 3, tvar: 0 },
{ tin: 'ावः', la: 'लट्', tip: 'वस्', size: 3, tvar: 0 },
{ tin: 'ामः', la: 'लट्', tip: 'मस्', size: 3, tvar: 0 },
{ tin: 'ते', la: 'लट्', tip: 'त', size: 2, tvar: 0 },
{ tin: 'ेते', la: 'लट्', tip: 'आताम्', size: 3, tvar: 0 },
{ tin: 'न्ते', la: 'लट्', tip: 'झ', size: 4, tvar: 0 },
{ tin: 'से', la: 'लट्', tip: 'थास्', size: 2, tvar: 0 },
{ tin: 'ेथे', la: 'लट्', tip: 'आथाम्', size: 3, tvar: 0 },
{ tin: 'ध्वे', la: 'लट्', tip: 'ध्वम्', size: 4, tvar: 0 },
{ tin: 'े', la: 'लट्', tip: 'इट्', size: 1, tvar: 0 },
{ tin: 'ावहे', la: 'लट्', tip: 'वहिङ', size: 4, tvar: 0 },
{ tin: 'ामहे', la: 'लट्', tip: 'महिङ', size: 4, tvar: 0 },
{ tin: 'त्', la: 'लङ्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'ताम्', la: 'लङ्', tip: 'तस्', size: 4, tvar: 0 },
{ tin: 'न्', la: 'लङ्', tip: 'झि', size: 2, tvar: 0 },
{ tin: 'ः', la: 'लङ्', tip: 'सिप्', size: 1, tvar: 0 },
{ tin: 'तम्', la: 'लङ्', tip: 'थस्', size: 3, tvar: 0 },
{ tin: 'त', la: 'लङ्', tip: 'थ', size: 1, tvar: 0 },
{ tin: 'म्', la: 'लङ्', tip: 'मिप्', size: 2, tvar: 0 },
{ tin: 'ाव', la: 'लङ्', tip: 'वस्', size: 2, tvar: 0 },
{ tin: 'ाम', la: 'लङ्', tip: 'मस्', size: 2, tvar: 0 },
{ tin: 'दत्', la: 'लङ्', tip: 'तिप्', size: 3, tvar: 1 },
{ tin: 'दताम्', la: 'लङ्', tip: 'तस्', size: 5, tvar: 1 },
{ tin: 'थन्', la: 'लङ्', tip: 'झि', size: 3, tvar: 1 },
{ tin: 'दः', la: 'लङ्', tip: 'सिप्', size: 2, tvar: 1 },
{ tin: 'दतम्', la: 'लङ्', tip: 'थस्', size: 4, tvar: 1 },
{ tin: 'दत', la: 'लङ्', tip: 'थ', size: 2, tvar: 1 },
{ tin: 'दम्', la: 'लङ्', tip: 'मिप्', size: 3, tvar: 1 },
{ tin: 'दाव', la: 'लङ्', tip: 'वस्', size: 3, tvar: 1 },
{ tin: 'दाम', la: 'लङ्', tip: 'मस्', size: 3, tvar: 1 },
{ tin: 'त', la: 'लङ्', tip: 'त', size: 1, tvar: 0 },
{ tin: 'ेताम्', la: 'लङ्', tip: 'आताम्', size: 5, tvar: 0 },
{ tin: 'न्त', la: 'लङ्', tip: 'झ', size: 3, tvar: 0 },
{ tin: 'थाः', la: 'लङ्', tip: 'थास्', size: 3, tvar: 0 },
{ tin: 'ेथाम्', la: 'लङ्', tip: 'आथाम्', size: 5, tvar: 0 },
{ tin: 'ध्वम्', la: 'लङ्', tip: 'ध्वम्', size: 5, tvar: 0 },
{ tin: 'े', la: 'लङ्', tip: 'इट्', size: 1, tvar: 0 },
{ tin: 'ावहि', la: 'लङ्', tip: 'वहिङ', size: 4, tvar: 0 },
{ tin: 'ामहि', la: 'लङ्', tip: 'महिङ', size: 4, tvar: 0 },
{ tin: 'ेथाः', la: 'लङ्', tip: 'थास्', size: 4, tvar: 1 },
{ tin: 'ूव', la: 'लिट्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'ूवतुः', la: 'लिट्', tip: 'तस्', size: 5, tvar: 0 },
{ tin: 'ूवुः', la: 'लिट्', tip: 'झि', size: 4, tvar: 0 },
{ tin: 'ूविथ', la: 'लिट्', tip: 'सिप्', size: 4, tvar: 0 },
{ tin: 'ुवथुः', la: 'लिट्', tip: 'थस्', size: 5, tvar: 0 },
{ tin: 'ूव', la: 'लिट्', tip: 'थ', size: 2, tvar: 0 },
{ tin: 'ूव', la: 'लिट्', tip: 'मिप्', size: 2, tvar: 0 },
{ tin: 'ुविव', la: 'लिट्', tip: 'वस्', size: 4, tvar: 0 },
{ tin: 'ूविम', la: 'लिट्', tip: 'मस्', size: 4, tvar: 0 },
{ tin: 'ेत', la: 'लिट्', tip: 'तिप्', size: 2, tvar: 1 },
{ tin: 'िततुः', la: 'लिट्', tip: 'तस्', size: 5, tvar: 1 },
{ tin: 'ितुः', la: 'लिट्', tip: 'झि', size: 4, tvar: 1 },
{ tin: 'ेतिथ', la: 'लिट्', tip: 'सिप्', size: 4, tvar: 1 },
{ tin: 'ितथुः', la: 'लिट्', tip: 'थस्', size: 5, tvar: 1 },
{ tin: 'ित', la: 'लिट्', tip: 'थ', size: 2, tvar: 1 },
{ tin: 'ेत', la: 'लिट्', tip: 'मिप्', size: 2, tvar: 1 },
{ tin: 'ितिव', la: 'लिट्', tip: 'वस्', size: 4, tvar: 1 },
{ tin: 'ितिम', la: 'लिट्', tip: 'मस्', size: 4, tvar: 1 },
{ tin: '्रे', la: 'लिट्', tip: 'त', size: 3, tvar: 0 },
{ tin: '्राते', la: 'लिट्', tip: 'आताम्', size: 5, tvar: 0 },
{ tin: '्रिरे', la: 'लिट्', tip: 'झ', size: 5, tvar: 0 },
{ tin: 'ृषे', la: 'लिट्', tip: 'थास्', size: 3, tvar: 0 },
{ tin: '्राथे', la: 'लिट्', tip: 'आथाम्', size: 5, tvar: 0 },
{ tin: '्रृढ्वे', la: 'लिट्', tip: 'ध्वम्', size: 7, tvar: 0 },
{ tin: '्रे', la: 'लिट्', tip: 'इट्', size: 3, tvar: 0 },
{ tin: '्रृवहे', la: 'लिट्', tip: 'वहिङ', size: 6, tvar: 0 },
{ tin: '्रृमहे', la: 'लिट्', tip: 'महिङ', size: 6, tvar: 0 },
{ tin: 'े', la: 'लिट्', tip: 'त', size: 1, tvar: 1 },
{ tin: 'ाते', la: 'लिट्', tip: 'आताम्', size: 3, tvar: 1 },
{ tin: 'िरे', la: 'लिट्', tip: 'झ', size: 3, tvar: 1 },
{ tin: 'िषे', la: 'लिट्', tip: 'थास्', size: 3, tvar: 1 },
{ tin: 'ाथे', la: 'लिट्', tip: 'आथाम्', size: 3, tvar: 1 },
{ tin: 'िध्वे', la: 'लिट्', tip: 'ध्वम्', size: 5, tvar: 1 },
{ tin: 'े', la: 'लिट्', tip: 'इट्', size: 1, tvar: 1 },
{ tin: 'िवहे', la: 'लिट्', tip: 'वहिङ', size: 4, tvar: 1 },
{ tin: 'िमहे', la: 'लिट्', tip: 'महिङ', size: 4, tvar: 1 },
{ tin: 'त्', la: 'लुङ्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'ताम्', la: 'लुङ्', tip: 'तस्', size: 4, tvar: 0 },
{ tin: 'वन्', la: 'लुङ्', tip: 'झि', size: 3, tvar: 0 },
{ tin: 'ः', la: 'लुङ्', tip: 'सिप्', size: 1, tvar: 0 },
{ tin: 'तम्', la: 'लुङ्', tip: 'थस्', size: 3, tvar: 0 },
{ tin: 'त', la: 'लुङ्', tip: 'थ', size: 1, tvar: 0 },
{ tin: 'वम्', la: 'लुङ्', tip: 'मिप्', size: 3, tvar: 0 },
{ tin: 'व', la: 'लुङ्', tip: 'वस्', size: 1, tvar: 0 },
{ tin: 'म', la: 'लुङ्', tip: 'मस्', size: 1, tvar: 0 },
{ tin: 'ीत्', la: 'लुङ्', tip: 'तिप्', size: 3, tvar: 1 },
{ tin: 'िष्टाम्', la: 'लुङ्', tip: 'तस्', size: 7, tvar: 1 },
{ tin: 'िषुः', la: 'लुङ्', tip: 'झि', size: 4, tvar: 1 },
{ tin: 'ीः', la: 'लुङ्', tip: 'सिप्', size: 2, tvar: 1 },
{ tin: 'िष्टम्', la: 'लुङ्', tip: 'थस्', size: 6, tvar: 1 },
{ tin: 'िष्ट', la: 'लुङ्', tip: 'थ', size: 4, tvar: 1 },
{ tin: 'िषम्', la: 'लुङ्', tip: 'मिप्', size: 4, tvar: 1 },
{ tin: 'िष्व', la: 'लुङ्', tip: 'वस्', size: 4, tvar: 1 },
{ tin: 'िष्म', la: 'लुङ्', tip: 'मस्', size: 4, tvar: 1 },
{ tin: 'ऐधिष्ट', la: 'लुङ्', tip: 'त', size: 6, tvar: 0 },
{ tin: 'एधिषाताम्', la: 'लुङ्', tip: 'आताम्', size: 9, tvar: 0 },
{ tin: 'ऐधिषत', la: 'लुङ्', tip: 'झ', size: 5, tvar: 0 },
{ tin: 'ऐधिष्ठाः', la: 'लुङ्', tip: 'थास्', size: 8, tvar: 0 },
{ tin: 'ऐधिषाथाम्', la: 'लुङ्', tip: 'आथाम्', size: 9, tvar: 0 },
{ tin: 'ऐधिध्वम्', la: 'लुङ्', tip: 'ध्वम्', size: 8, tvar: 0 },
{ tin: 'ऐधिषि', la: 'लुङ्', tip: 'इट्', size: 5, tvar: 0 },
{ tin: 'ऐधिष्वहि', la: 'लुङ्', tip: 'वहिङ', size: 8, tvar: 0 },
{ tin: 'ऐधिष्महि', la: 'लुङ्', tip: 'महिङ', size: 8, tvar: 0 },
{ tin: 'ष्ट', la: 'लुङ्', tip: 'त', size: 3, tvar: 1 },
{ tin: 'षाताम्', la: 'लुङ्', tip: 'आताम्', size: 6, tvar: 1 },
{ tin: 'षत', la: 'लुङ्', tip: 'झ', size: 2, tvar: 1 },
{ tin: 'ष्ठाः', la: 'लुङ्', tip: 'थास्', size: 5, tvar: 1 },
{ tin: 'षाथाम्', la: 'लुङ्', tip: 'आथाम्', size: 6, tvar: 1 },
{ tin: 'ध्वम्', la: 'लुङ्', tip: 'ध्वम्', size: 5, tvar: 1 },
{ tin: 'षि', la: 'लुङ्', tip: 'इट्', size: 2, tvar: 1 },
{ tin: 'ष्वहि', la: 'लुङ्', tip: 'वहिङ', size: 5, tvar: 1 },
{ tin: 'ष्महि', la: 'लुङ्', tip: 'महिङ', size: 5, tvar: 1 },
{ tin: '', la: 'लुट्', tip: 'तिप्', size: 0, tvar: 0 },
{ tin: 'रौ', la: 'लुट्', tip: 'तस्', size: 2, tvar: 0 },
{ tin: 'रः', la: 'लुट्', tip: 'झि', size: 2, tvar: 0 },
{ tin: 'सि', la: 'लुट्', tip: 'सिप्', size: 2, tvar: 0 },
{ tin: 'स्थः', la: 'लुट्', tip: 'थस्', size: 4, tvar: 0 },
{ tin: 'स्थ', la: 'लुट्', tip: 'थ', size: 3, tvar: 0 },
{ tin: 'स्मि', la: 'लुट्', tip: 'मिप्', size: 4, tvar: 0 },
{ tin: 'स्वः', la: 'लुट्', tip: 'वस्', size: 4, tvar: 0 },
{ tin: 'स्मः', la: 'लुट्', tip: 'मस्', size: 4, tvar: 0 },
{ tin: 'न्दिता', la: 'लुट्', tip: 'तिप्', size: 6, tvar: 1 },
{ tin: 'न्दितारौ', la: 'लुट्', tip: 'तस्', size: 8, tvar: 1 },
{ tin: 'दितारः', la: 'लुट्', tip: 'झि', size: 6, tvar: 1 },
{ tin: 'न्दितासि', la: 'लुट्', tip: 'सिप्', size: 8, tvar: 1 },
{ tin: 'न्दितास्थः', la: 'लुट्', tip: 'थस्', size: 10, tvar: 1 },
{ tin: 'न्दितास्थ', la: 'लुट्', tip: 'थ', size: 9, tvar: 1 },
{ tin: 'न्दितास्मि', la: 'लुट्', tip: 'मिप्', size: 10, tvar: 1 },
{ tin: 'न्दितास्वः', la: 'लुट्', tip: 'वस्', size: 10, tvar: 1 },
{ tin: 'न्दितास्मः', la: 'लुट्', tip: 'मस्', size: 10, tvar: 1 },
{ tin: '', la: 'लुट्', tip: 'त', size: 0, tvar: 0 },
{ tin: 'रौ', la: 'लुट्', tip: 'आताम्', size: 2, tvar: 0 },
{ tin: 'रः', la: 'लुट्', tip: 'झ', size: 2, tvar: 0 },
{ tin: 'से', la: 'लुट्', tip: 'थास्', size: 2, tvar: 0 },
{ tin: 'साथे', la: 'लुट्', tip: 'आथाम्', size: 4, tvar: 0 },
{ tin: 'ध्वे', la: 'लुट्', tip: 'ध्वम्', size: 4, tvar: 0 },
{ tin: 'हे', la: 'लुट्', tip: 'इट्', size: 2, tvar: 0 },
{ tin: 'स्वहे', la: 'लुट्', tip: 'वहिङ', size: 5, tvar: 0 },
{ tin: 'स्महे', la: 'लुट्', tip: 'महिङ', size: 5, tvar: 0 },
{ tin: 'क्षिता', la: 'लुट्', tip: 'त', size: 6, tvar: 1 },
{ tin: 'क्षितारौ', la: 'लुट्', tip: 'आताम्', size: 8, tvar: 1 },
{ tin: 'क्षितारः', la: 'लुट्', tip: 'झ', size: 8, tvar: 1 },
{ tin: 'क्षितासे', la: 'लुट्', tip: 'थास्', size: 8, tvar: 1 },
{ tin: 'षितासाथे', la: 'लुट्', tip: 'आथाम्', size: 8, tvar: 1 },
{ tin: 'क्षिताध्वे', la: 'लुट्', tip: 'ध्वम्', size: 10, tvar: 1 },
{ tin: 'क्षिताहे', la: 'लुट्', tip: 'इट्', size: 8, tvar: 1 },
{ tin: 'क्षितास्वहे', la: 'लुट्', tip: 'वहिङ', size: 11, tvar: 1 },
{ tin: 'क्षितास्महे', la: 'लुट्', tip: 'महिङ', size: 11, tvar: 1 },
{ tin: 'ति', la: 'ऌट्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'तः', la: 'ऌट्', tip: 'तस्', size: 2, tvar: 0 },
{ tin: 'न्ति', la: 'ऌट्', tip: 'झि', size: 4, tvar: 0 },
{ tin: 'सि', la: 'ऌट्', tip: 'सिप्', size: 2, tvar: 0 },
{ tin: 'थः', la: 'ऌट्', tip: 'थस्', size: 2, tvar: 0 },
{ tin: 'थ', la: 'ऌट्', tip: 'थ', size: 1, tvar: 0 },
{ tin: 'ामि', la: 'ऌट्', tip: 'मिप्', size: 3, tvar: 0 },
{ tin: 'ावः', la: 'ऌट्', tip: 'वस्', size: 3, tvar: 0 },
{ tin: 'ामः', la: 'ऌट्', tip: 'मस्', size: 3, tvar: 0 },
{ tin: 'ते', la: 'ऌट्', tip: 'त', size: 2, tvar: 0 },
{ tin: 'ेते', la: 'ऌट्', tip: 'आताम्', size: 3, tvar: 0 },
{ tin: 'न्ते', la: 'ऌट्', tip: 'झ', size: 4, tvar: 0 },
{ tin: 'से', la: 'ऌट्', tip: 'थास्', size: 2, tvar: 0 },
{ tin: 'ेथे', la: 'ऌट्', tip: 'आथाम्', size: 3, tvar: 0 },
{ tin: 'ध्वे', la: 'ऌट्', tip: 'ध्वम्', size: 4, tvar: 0 },
{ tin: 'े', la: 'ऌट्', tip: 'इट्', size: 1, tvar: 0 },
{ tin: 'ावहे', la: 'ऌट्', tip: 'वहिङ', size: 4, tvar: 0 },
{ tin: 'ामहे', la: 'ऌट्', tip: 'महिङ', size: 4, tvar: 0 },
{ tin: 'तु', la: 'लोट्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'ताम्', la: 'लोट्', tip: 'तस्', size: 4, tvar: 0 },
{ tin: 'न्तु', la: 'लोट्', tip: 'झि', size: 4, tvar: 0 },
{ tin: '', la: 'लोट्', tip: 'सिप्', size: 0, tvar: 0 },
{ tin: 'तम्', la: 'लोट्', tip: 'थस्', size: 3, tvar: 0 },
{ tin: 'त', la: 'लोट्', tip: 'थ', size: 1, tvar: 0 },
{ tin: 'ानि', la: 'लोट्', tip: 'मिप्', size: 3, tvar: 0 },
{ tin: 'ाव', la: 'लोट्', tip: 'वस्', size: 2, tvar: 0 },
{ tin: 'ाम', la: 'लोट्', tip: 'मस्', size: 2, tvar: 0 },
{ tin: 'ाणि', la: 'लोट्', tip: 'मिप्', size: 3, tvar: 1 },
{ tin: 'ताम्', la: 'लोट्', tip: 'त', size: 4, tvar: 0 },
{ tin: 'ेताम्', la: 'लोट्', tip: 'आताम्', size: 5, tvar: 0 },
{ tin: 'न्ताम्', la: 'लोट्', tip: 'झ', size: 6, tvar: 0 },
{ tin: 'स्व', la: 'लोट्', tip: 'थास्', size: 3, tvar: 0 },
{ tin: 'ेथाम्', la: 'लोट्', tip: 'आथाम्', size: 5, tvar: 0 },
{ tin: 'ध्वम्', la: 'लोट्', tip: 'ध्वम्', size: 5, tvar: 0 },
{ tin: 'ै', la: 'लोट्', tip: 'इट्', size: 1, tvar: 0 },
{ tin: 'ावहै', la: 'लोट्', tip: 'वहिङ', size: 4, tvar: 0 },
{ tin: 'ामहै', la: 'लोट्', tip: 'महिङ', size: 4, tvar: 0 },
{ tin: 'िताम्', la: 'लोट्', tip: 'त', size: 5, tvar: 1 },
{ tin: 'त्', la: 'विधिलिङ्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'ताम्', la: 'विधिलिङ्', tip: 'तस्', size: 4, tvar: 0 },
{ tin: 'युः', la: 'विधिलिङ्', tip: 'झि', size: 3, tvar: 0 },
{ tin: 'ः', la: 'विधिलिङ्', tip: 'सिप्', size: 1, tvar: 0 },
{ tin: 'तम्', la: 'विधिलिङ्', tip: 'थस्', size: 3, tvar: 0 },
{ tin: 'त', la: 'विधिलिङ्', tip: 'थ', size: 1, tvar: 0 },
{ tin: 'यम्', la: 'विधिलिङ्', tip: 'मिप्', size: 3, tvar: 0 },
{ tin: 'व', la: 'विधिलिङ्', tip: 'वस्', size: 1, tvar: 0 },
{ tin: 'म', la: 'विधिलिङ्', tip: 'मस्', size: 1, tvar: 0 },
{ tin: 'ेत्', la: 'विधिलिङ्', tip: 'तिप्', size: 3, tvar: 1 },
{ tin: 'ेताम्', la: 'विधिलिङ्', tip: 'तस्', size: 5, tvar: 1 },
{ tin: 'ेयुः', la: 'विधिलिङ्', tip: 'झि', size: 4, tvar: 1 },
{ tin: 'ेः', la: 'विधिलिङ्', tip: 'सिप्', size: 2, tvar: 1 },
{ tin: 'ेतम्', la: 'विधिलिङ्', tip: 'थस्', size: 4, tvar: 1 },
{ tin: 'ेत', la: 'विधिलिङ्', tip: 'थ', size: 2, tvar: 1 },
{ tin: 'ेयम्', la: 'विधिलिङ्', tip: 'मिप्', size: 4, tvar: 1 },
{ tin: 'ाव', la: 'विधिलिङ्', tip: 'वस्', size: 2, tvar: 1 },
{ tin: 'ाम', la: 'विधिलिङ्', tip: 'मस्', size: 2, tvar: 1 },
{ tin: 'त', la: 'विधिलिङ्', tip: 'त', size: 1, tvar: 0 },
{ tin: 'याताम्', la: 'विधिलिङ्', tip: 'आताम्', size: 6, tvar: 0 },
{ tin: 'रन्', la: 'विधिलिङ्', tip: 'झ', size: 3, tvar: 0 },
{ tin: 'थाः', la: 'विधिलिङ्', tip: 'थास्', size: 3, tvar: 0 },
{ tin: 'याथाम्', la: 'विधिलिङ्', tip: 'आथाम्', size: 6, tvar: 0 },
{ tin: 'यध्वम्', la: 'विधिलिङ्', tip: 'ध्वम्', size: 6, tvar: 0 },
{ tin: 'य', la: 'विधिलिङ्', tip: 'इट्', size: 1, tvar: 0 },
{ tin: 'वहि', la: 'विधिलिङ्', tip: 'वहिङ', size: 3, tvar: 0 },
{ tin: 'महि', la: 'विधिलिङ्', tip: 'महिङ', size: 3, tvar: 0 },
{ tin: 'ध्वम्', la: 'विधिलिङ्', tip: 'ध्वम्', size: 5, tvar: 1 },
{ tin: 'त्', la: 'आशीर्लिङ्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'स्ताम्', la: 'आशीर्लिङ्', tip: 'तस्', size: 6, tvar: 0 },
{ tin: 'सुः', la: 'आशीर्लिङ्', tip: 'झि', size: 3, tvar: 0 },
{ tin: 'ः', la: 'आशीर्लिङ्', tip: 'सिप्', size: 1, tvar: 0 },
{ tin: 'स्तम्', la: 'आशीर्लिङ्', tip: 'थस्', size: 5, tvar: 0 },
{ tin: 'स्त', la: 'आशीर्लिङ्', tip: 'थ', size: 3, tvar: 0 },
{ tin: 'सम्', la: 'आशीर्लिङ्', tip: 'मिप्', size: 3, tvar: 0 },
{ tin: 'स्व', la: 'आशीर्लिङ्', tip: 'वस्', size: 3, tvar: 0 },
{ tin: 'स्म', la: 'आशीर्लिङ्', tip: 'मस्', size: 3, tvar: 0 },
{ tin: '्त्यात्', la: 'आशीर्लिङ्', tip: 'तिप्', size: 7, tvar: 1 },
{ tin: '्त्यास्ताम्',
  la: 'आशीर्लिङ्',
  tip: 'तस्',
  size: 11,
  tvar: 1 },
{ tin: 'त्यासुः', la: 'आशीर्लिङ्', tip: 'झि', size: 7, tvar: 1 },
{ tin: 'त्याः', la: 'आशीर्लिङ्', tip: 'सिप्', size: 5, tvar: 1 },
{ tin: '्त्यास्तम्',
  la: 'आशीर्लिङ्',
  tip: 'थस्',
  size: 10,
  tvar: 1 },
{ tin: '्त्यास्त', la: 'आशीर्लिङ्', tip: 'थ', size: 8, tvar: 1 },
{ tin: '्त्यासम्', la: 'आशीर्लिङ्', tip: 'मिप्', size: 8, tvar: 1 },
{ tin: '्त्यास्व', la: 'आशीर्लिङ्', tip: 'वस्', size: 8, tvar: 1 },
{ tin: '्त्यास्म', la: 'आशीर्लिङ्', tip: 'मस्', size: 8, tvar: 1 },
{ tin: 'ष्ट', la: 'आशीर्लिङ्', tip: 'त', size: 3, tvar: 0 },
{ tin: 'यास्ताम्',
  la: 'आशीर्लिङ्',
  tip: 'आताम्',
  size: 8,
  tvar: 0 },
{ tin: 'रन्', la: 'आशीर्लिङ्', tip: 'झ', size: 3, tvar: 0 },
{ tin: 'ष्ठाः', la: 'आशीर्लिङ्', tip: 'थास्', size: 5, tvar: 0 },
{ tin: 'यास्थाम्',
  la: 'आशीर्लिङ्',
  tip: 'आथाम्',
  size: 8,
  tvar: 0 },
{ tin: 'ध्वम्', la: 'आशीर्लिङ्', tip: 'ध्वम्', size: 5, tvar: 0 },
{ tin: 'य', la: 'आशीर्लिङ्', tip: 'इट्', size: 1, tvar: 0 },
{ tin: 'वहि', la: 'आशीर्लिङ्', tip: 'वहिङ', size: 3, tvar: 0 },
{ tin: 'महि', la: 'आशीर्लिङ्', tip: 'महिङ', size: 3, tvar: 0 },
{ tin: 'षीष्ट', la: 'आशीर्लिङ्', tip: 'त', size: 5, tvar: 1 },
{ tin: 'षीयास्ताम्',
  la: 'आशीर्लिङ्',
  tip: 'आताम्',
  size: 10,
  tvar: 1 },
{ tin: 'षीरन्', la: 'आशीर्लिङ्', tip: 'झ', size: 5, tvar: 1 },
{ tin: 'षीष्ठाः', la: 'आशीर्लिङ्', tip: 'थास्', size: 7, tvar: 1 },
{ tin: 'षीयास्थाम्',
  la: 'आशीर्लिङ्',
  tip: 'आथाम्',
  size: 10,
  tvar: 1 },
{ tin: 'षीय', la: 'आशीर्लिङ्', tip: 'इट्', size: 3, tvar: 1 },
{ tin: 'षीवहि', la: 'आशीर्लिङ्', tip: 'वहिङ', size: 5, tvar: 1 },
{ tin: 'षीमहि', la: 'आशीर्लिङ्', tip: 'महिङ', size: 5, tvar: 1 },
{ tin: 'त्', la: 'ॡङ्', tip: 'तिप्', size: 2, tvar: 0 },
{ tin: 'ताम्', la: 'ॡङ्', tip: 'तस्', size: 4, tvar: 0 },
{ tin: 'न्', la: 'ॡङ्', tip: 'झि', size: 2, tvar: 0 },
{ tin: 'ः', la: 'ॡङ्', tip: 'सिप्', size: 1, tvar: 0 },
{ tin: 'तम्', la: 'ॡङ्', tip: 'थस्', size: 3, tvar: 0 },
{ tin: 'त', la: 'ॡङ्', tip: 'थ', size: 1, tvar: 0 },
{ tin: 'म्', la: 'ॡङ्', tip: 'मिप्', size: 2, tvar: 0 },
{ tin: 'ाव', la: 'ॡङ्', tip: 'वस्', size: 2, tvar: 0 },
{ tin: 'ाम', la: 'ॡङ्', tip: 'मस्', size: 2, tvar: 0 },
{ tin: 'िन्दिष्यत्', la: 'ॡङ्', tip: 'तिप्', size: 10, tvar: 1 },
{ tin: 'िन्दिष्यताम्', la: 'ॡङ्', tip: 'तस्', size: 12, tvar: 1 },
{ tin: 'िन्दिष्यन्', la: 'ॡङ्', tip: 'झि', size: 10, tvar: 1 },
{ tin: 'िन्दिष्यः', la: 'ॡङ्', tip: 'सिप्', size: 9, tvar: 1 },
{ tin: 'िन्दिष्यतम्', la: 'ॡङ्', tip: 'थस्', size: 11, tvar: 1 },
{ tin: 'र्दिष्यत', la: 'ॡङ्', tip: 'थ', size: 8, tvar: 1 },
{ tin: 'िन्दिष्यम्', la: 'ॡङ्', tip: 'मिप्', size: 10, tvar: 1 },
{ tin: 'िन्दिष्याव', la: 'ॡङ्', tip: 'वस्', size: 10, tvar: 1 },
{ tin: 'िन्दिष्याम', la: 'ॡङ्', tip: 'मस्', size: 10, tvar: 1 },
{ tin: 'त', la: 'ॡङ्', tip: 'त', size: 1, tvar: 0 },
{ tin: 'ेताम्', la: 'ॡङ्', tip: 'आताम्', size: 5, tvar: 0 },
{ tin: 'न्त', la: 'ॡङ्', tip: 'झ', size: 3, tvar: 0 },
{ tin: 'थाः', la: 'ॡङ्', tip: 'थास्', size: 3, tvar: 0 },
{ tin: 'ेथाम्', la: 'ॡङ्', tip: 'आथाम्', size: 5, tvar: 0 },
{ tin: 'ध्वम्', la: 'ॡङ्', tip: 'ध्वम्', size: 5, tvar: 0 },
{ tin: 'े', la: 'ॡङ्', tip: 'इट्', size: 1, tvar: 0 },
{ tin: 'ावहि', la: 'ॡङ्', tip: 'वहिङ', size: 4, tvar: 0 },
{ tin: 'ामहि', la: 'ॡङ्', tip: 'महिङ', size: 4, tvar: 0 },
{ tin: 'यत', la: 'ॡङ्', tip: 'त', size: 2, tvar: 1 },
{ tin: 'येताम्', la: 'ॡङ्', tip: 'आताम्', size: 6, tvar: 1 },
{ tin: 'यन्त', la: 'ॡङ्', tip: 'झ', size: 4, tvar: 1 },
{ tin: 'यथाः', la: 'ॡङ्', tip: 'थास्', size: 4, tvar: 1 },
{ tin: 'कियेथाम्', la: 'ॡङ्', tip: 'आथाम्', size: 8, tvar: 1 },
{ tin: 'यध्वम्', la: 'ॡङ्', tip: 'ध्वम्', size: 6, tvar: 1 },
{ tin: 'ये', la: 'ॡङ्', tip: 'इट्', size: 2, tvar: 1 },
{ tin: 'यावहि', la: 'ॡङ्', tip: 'वहिङ', size: 5, tvar: 1 },
{ tin: 'यामहि', la: 'ॡङ्', tip: 'महिङ', size: 5, tvar: 1 },
]; 
exports = module.exports = data;